### ISSUE TITLE
Trying to build in Docker container fails undeclared

### ISSUE THREAD

**Issue by JohnOmernik** [edenhill/kafkacat#100]
I am trying to build this in docker not sure if I missing something in my container in general, or not setting something properly... (I am a bit new to building things)

Thanks!

gcc -MD -MP -I/opt/mapr/include -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith  -c kafkacat.c -o kafkacat.o
gcc -MD -MP -I/opt/mapr/include -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith  -c format.c -o format.o
format.c: In function 'fmt_msg_output_str':
format.c:190:17: warning: enumeration value 'KC_FMT_TIMESTAMP' not handled in switch [-Wswitch]
                 switch (conf.fmt[i].type)
                 ^
format.c:187:21: warning: variable 'r' set but not used [-Wunused-but-set-variable]
                 int r = 1;
                     ^
format.c:262:21: error: 'r' undeclared (first use in this function)
                 if (r < 1)
                     ^
format.c:262:21: note: each undeclared identifier is reported only once for each function it appears in
format.c: At top level:
format.c:269:1: error: expected identifier or '(' before '}' token
 }
 ^
make: *** [format.o] Error 1
mklove/Makefile.base:77: recipe for target 'format.o' failed

**Comment by edenhill** [comment]
It looks like your librdkafka version is too old.

Try installing librdkafka v0.9.5  (librdkafka-dev) and try again

**Comment by JohnOmernik** [comment]
Thanks, that helps me find the issue!
