### ISSUE TITLE
Add support for reading configuration from file

### ISSUE THREAD

**Issue by LionelCons** [edenhill/kafkacat#101]
rdkafka_performance.c supports a configuration file via `-X file=<path>`.

It would be very useful to have the same feature in kafkacat.

**Comment by edenhill** [comment]
kafkacat now supports `-F <config-file>` which defaults to ~/.ccloud/config (confluent cloud settings).
note: If an unwanted ccloud/config file is in place, use `-F none` to ignore it.

**Comment by StevoKe** [comment]
Does this still work for kafkacat version 1.3.1 and ccloud version 1.0.0?

**Comment by edenhill** [comment]
It should work unless the ccloud config format changed, give it a try.

**Comment by StevoKe** [comment]
It didn't work for me.
It seems that the config file use to be a property file. Now it has a JSON format.
