### ISSUE TITLE
Kafkacat and 0.10+ consumers

### ISSUE THREAD

**Issue by jcmuller** [edenhill/kafkacat#103]
Is it possible to have `kafkacat` produce messages compatible with 0.10+ consumers?

Getting "Input record ConsumerRecord........ has invalid (negative) timestamp. Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+."

How would you suggest I work around this?

Regards!

**Comment by edenhill** [comment]
Specify `-X api.version.request=true` on the kafkacat command line to enable >=0.10 features.
