### ISSUE TITLE
Not able to get the latest record

### ISSUE THREAD

**Issue by fuji246** [edenhill/kafkacat#104]
Giving a topic with multiple partitions, using the following command won't be able to get the latest record.

```
 kafkacat -b 10.22.132.131:9092 -t bt1-mbr-shutter-video-csg-hdfs -o -1 -e -c 1
```

with only 1 partition  topic, no problem, however when multiple partitions, kafkacat just return the last record of one partition and then quit, it might not be the latest one.

If there if any other command option to do this, will close this issue.

**Comment by edenhill** [comment]
Since you are giving it a maximum count of 1 message to consume through `-c 1` I would say this is expected behaviour. Remove the `-c 1` option.

**Comment by fuji246** [comment]
remove "-c 1" combines the last records of each partition, not the latest one, i think

**Comment by edenhill** [comment]
`-c ..` is a global message counter, it simply counts the number of messages printed and exits when this number is reached, regardless of partition.
