### ISSUE TITLE
Kafkacat returns no records but shows non-zero offsets

### ISSUE THREAD

**Issue by javierholguera** [edenhill/kafkacat#105]
Hi,

When I tried to consume a certain topic my-topic, I don't get any records back. However, kafkacat does report this:

```bash
$ ./kafkacat -C -e -t my-topic -f 'Topic %t[%p], offset: %o, key: %k, Timestamp: %T \n' -b kafka-broker:9092 -X 'security.protocol=ssl' -X 'ssl.ca.location=ca_public.crt' -X 'ssl.certificate.location=client.crt' -X 'ssl.key.location=client.key' -X 'ssl.key.password=password'

% Reached end of topic my-topic [3] at offset 3951 
% Reached end of topic my-topic [0] at offset 3872 
% Reached end of topic my-topic [2] at offset 3676 
% Reached end of topic my-topic [1] at offset 3747: exiting
```

It does return events for other topics, though. Also, using `kafka-console-consumer` I can read some of the events in this topic, although surprisingly it only returns 176 despite what the offsets suggest. I don't think this is a compacted topic or that the retention policy should have already truncated data in it.

We had a consumer of this topic reporting this error a few days ago:
```
Input record ConsumerRecord(topic = my-topic, partition = 0, offset = 1368, CreateTime = -1, checksum = 1465117883, serialized key size = 36, serialized value size = 294, key = 7466477c-5051-e711-8188-0aa21f96199f, value = { -- REDACTED -- }) has invalid (negative) timestamp. Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+. Use a different TimestampExtractor to process this data
```
Don't know if it could be related. Kafkacat still doesn't return anything with a -f format without timestamp.

We produce to this topic using librdkafka / confluent-dotnet client with api.version.request=true, btw.

**Comment by edenhill** [comment]
kafkacat starts consuming from the end of the partition by default, and if there are no new messages being produced to the topic and kafkacat hits the end of the partition it will exit if the `-e` flag is used.

If you want to read from the beginning, try `-o beginning` or `-o -1000` to read the last 1000 messages for each partition.
If you want to consume a specific offset you can use `-p 0 -o 1368 -c 1`

**Comment by javierholguera** [comment]
Thanks for your quick answer, that worked great.
