### ISSUE TITLE
E: Unable to locate package kafkacat on Ubuntu 14.04

### ISSUE THREAD

**Issue by kant111** [edenhill/kafkacat#106]
I tried the following

`sudo apt-get update`
`sudo apt-get install librdkafka-dev libyajl-dev`
`sudo apt-get install kafkacat`

I get the following error on Ubuntu 14.04
`E: Unable to locate package kafkacat`

What repo do I need to add?

**Comment by edenhill** [comment]
kafkacat was added to Ubuntu 16.04.
Suggest you build and install kafkacat from source.

**Comment by cjolif** [comment]
does not seem to work on Xenial either, at least for me.

**Comment by cjolif** [comment]
sorry was missing an update.
