### ISSUE TITLE
kafkacat -P stops producing when the leader disappears

### ISSUE THREAD

**Issue by owbear** [edenhill/kafkacat#108]
We've noticed that if the leaders networking is deconfigured (with ```ifconfig eth0 down```) the ```kafkacat -P``` producer won't notice this and doesn't connect to the newly elected leader.

```docker-compose.yml``` and test runners are at https://github.com/owbear/kafka-network-failure-tests with sample test output at https://github.com/owbear/kafka-network-failure-tests/blob/master/README.md#sample-results

I was expecting a transparent failover to the new leader.

**Comment by edenhill** [comment]
Try enabling tcp keepalives (see config guide) to expedite connection loss
detection

Den 29 jun 2017 15:22 skrev "owbear" <notifications@github.com>:

**Comment by owbear** [comment]
I added ```-X socket.keepalive.enable=true``` to enable this but say no change in what kafkacat manages to produce.
I'll try with ```socket.timeout.ms=2000``` as well.

**Comment by owbear** [comment]
```socket.timeout.ms=2000``` didn't help either I'm afraid

**Comment by edenhill** [comment]
This is fixed on librdkafka master
