### ISSUE TITLE
Does kafkacat support ssl connetion to kafka broker?

### ISSUE THREAD

**Issue by xingao0803** [edenhill/kafkacat#113]
1. Enable ssl on kafka broker
2. Install kafkacat: apt -y install kafkacat
3. Run: 
kafkacat -C -b :9092 -t topic2 -u -o end -X security.protocol=SSL -X ssl.ca.location=ca-cert -X ssl.key.password=password
get error: % ERROR: No such configuration property: "security.protocol"

How to enable ssl connection in kafkacat?
Thanks.

**Comment by edenhill** [comment]
what version of kafkacat and librdkafka are you using?

**Comment by xingao0803** [comment]
Usage: kafkacat <options> [file1 file2 ..]
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2015, Magnus Edenhill
Version KAFKACAT_VERSION (JSON) (librdkafka 0.8.6)

**Comment by edenhill** [comment]
That's very old.
Install the latest version of librdkafka from here:
http://docs.confluent.io/current/installation.html#installation-apt

**Comment by xingao0803** [comment]
I installed latest version of librdkafka, 
```Preparing to unpack .../librdkafka-dev_0.8.6-1.1_amd64.deb ...
Unpacking librdkafka-dev:amd64 (0.8.6-1.1) ...
Setting up librdkafka-dev:amd64 (0.8.6-1.1) ...```

But the kafkacat still uses the old librdkafka, 
```Version KAFKACAT_VERSION (JSON) (librdkafka 0.8.6)```

How could I update kafkacat to use the new librdkafka? to support ssl connection?

Thanks.

**Comment by edenhill** [comment]
The latest version of librdkafka is v0.11.0, not 0.8.6.
Add the Confluent APT repository as instructed in the link above and upgrade librdkafka to version v0.11.0
