### ISSUE TITLE
How to connect to kafka broker by  security.protocol=SASL_SSL and sasl.mechanisms=PLAIN

### ISSUE THREAD

**Issue by xingao0803** [edenhill/kafkacat#115]
My kafkacat and librdkafka are:
`apt-show-versions | grep kafka`
`kafkacat:amd64/xenial 1.2.0-2 uptodate`
`librdkafka++1:amd64/stable 0.11.0~1confluent3.3.0-1 uptodate`
`librdkafka-dev:amd64/stable 0.11.0~1confluent3.3.0-1 uptodate`
`librdkafka1:amd64/stable 0.11.0~1confluent3.3.0-1 uptodate`
and 
`apt-show-versions | grep sasl`
`libsasl2-2:amd64/xenial 2.1.26.dfsg1-14build1 uptodate`
`libsasl2-modules:amd64/xenial 2.1.26.dfsg1-14build1 uptodate`
`libsasl2-modules-db:amd64/xenial 2.1.26.dfsg1-14build1 uptodate`
`libsasl2-modules-gssapi-mit:amd64/xenial 2.1.26.dfsg1-14build1 uptodate`

**Comment by xingao0803** [comment]
When connect to kafka broker which enabled security.protocol=SASL_SSL and sasl.mechanisms=PLAIN like:
`kafkacat -C -b <broker>:9092 -t topic -u -o end -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN  -X sasl.username=<user> -X sasl.password=<pass> -X ssl.key.location=./kafka.client.truststore.jks -X ssl.key.password=<key-pass> -X ssl.ca.location=./ca-cert 
`
I got error:
`%3|1505223116.779|SSL|rdkafka#consumer-1| [thrd:app]: pem_lib.c:701: error:0906D06C:PEM routines:PEM_read_bio:no start line: Expecting: ANY PRIVATE KEY`
`% ERROR: Failed to create producer: ssl.key.location failed: ssl_rsa.c:649: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib:`

**Comment by xingao0803** [comment]
Where wrong? Did I miss any properties? or Did I set some properties wrong?
How to connect kafka broker which enabled security.protocol=SASL_SSL and sasl.mechanisms=PLAIN?

Thanks.

**Comment by edenhill** [comment]
Did you search google for the error message?
Google "no start line: Expecting: ANY PRIVATE KEY"

**Comment by xingao0803** [comment]
Resolved. Since there is no client_auth on kafka broker, so no ssl.key.location=./kafka.client.truststore.jks needed.
