### ISSUE TITLE
Update docs with useful params

### ISSUE THREAD

**Issue by sweco-seponr** [edenhill/kafkacat#116]
Suggest to add example to README.md 

Assuming you for some reason have allowed 5Mb messages in your broker cluster and you want to consume them then set them using -X flag like so:

    kafkacat -C -X fetch.message.max.bytes=5242880 -b mybroker -t mytopic

**Comment by edenhill** [comment]
librdkafka >=v0.9.2 will automatically adjust fetch.message.max.bytes upwards until a full Message can be received, so this shouldn't be needed.
What version of librdkafka are you using?

**Comment by sweco-seponr** [comment]
I ´m using  an unversioned(1) homebrew build on osx:
Usage: kafkacat <options> [file1 file2 ..]
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2015, Magnus Edenhill
Version KAFKACAT_VERSION (librdkafka 0.8.6)

So I´ll upgrade :-) Thanx for the pointer!
