### ISSUE TITLE
Query offset by timestamp

### ISSUE THREAD

**Issue by rohinivasu** [edenhill/kafkacat#117]
Hi,

I am trying to read the offset at a given point of time from a topic by following the commands from the readme document as shown below:
kafkacat -b mybroker -Q -t mytopic:3:2389238523  mytopic2:0:18921841

logstashtest:/appserver/kafkacat # ./kafkacat -b broker -Q -t topic:3:1506038400
logstashtest:/appserver/kafkacat # ./kafkacat -b broker -Q -o beginning -t topic:3:1506038400

it does'nt return any offset for me, instead below line is displayed with the same timestamp that i send:
topic [3] offset 150603840

Am I missing something here?

**Comment by edenhill** [comment]
What librdkafka version? (`kafkacat -V`) and what broker version?

**Comment by nitin456** [comment]
@edenhill 
I am running this utility to fetch offset by timestamp but I get error stating that -Q is not supported option. 
My Kafka version is 1.0.2
Version KAFKACAT_VERSION (JSON) (librdkafka 0.9.3) 

Can you please help here.

**Comment by edenhill** [comment]
Upgrade kafkacat and librdkafka
