### ISSUE TITLE
kafkacat accepts malformed '-b' parameter

### ISSUE THREAD

**Issue by wushujames** [edenhill/kafkacat#121]
I have a broker running on 127.0.0.1. I accidentially mistyped the ip address (left out some periods), and kafkacat still managed to understand it.

See repro below. I passed in `127.001`

```
$ kafkacat -L -b 127.001
Metadata for all topics (from broker -1: 127.001:9092/bootstrap):
 1 brokers:
  broker 0 at 192.168.0.108:9092
 1 topics:
  topic "test" with 1 partitions:
    partition 0, leader 0, replicas: 0, isrs: 0
$
```

**Comment by edenhill** [comment]
That's a valid IPv4 in the truncated format.
A.B.C.D can be truncated to:
 * .D -> 0.0.0.D
 * A.D -> A.0.0.D
 * A.C.D -> A.0.C.D

 Thus 127.001 -> 127.0.0.001 -> 127.0.0.1

**Comment by wushujames** [comment]
Waaat? Really? Is that just intended for human-readable stuff, or do computers take advantage of that to use a variable number of bytes to encode an IPv4 address?

**Comment by edenhill** [comment]
I would say it is aimed at aiding humans, this is only for the textual (input) representation of IPv4 addresses.
Note that IPv6 addresses have truncation as well using "::".
