### ISSUE TITLE
Failed to verify broker certificate: unable to get local issuer certificate

### ISSUE THREAD

**Issue by tukushan** [edenhill/kafkacat#124]
I'm getting  

`unable to get local issuer certificate` 

when using kafacat with 

`-X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN -X sasl.username=user -X sasl.password=pass`

I'm using

```
$ kafkacat -V       
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2015, Magnus Edenhill
Version KAFKACAT_VERSION (JSON) (librdkafka 0.9.3)

$ dpkg-query -W kafkacat librdkafka1 libsasl2-2 libssl1.0.0 
kafkacat	1.3.0-1
librdkafka1:amd64	0.9.3-1
libsasl2-2:amd64	2.1.27~101-g0780600+dfsg-2ubuntu1
libssl1.0.0:amd64	1.0.2g-1ubuntu11.2

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

Seems to work through when I compile master using bootstrap.sh.
Is the distributed .deb package not compiled with sasl or ssl support?

**Comment by edenhill** [comment]
librdkafka <0.11.0 did not fall back on the default system-installed CA certs when no ssl.ca.location was specified.
