### ISSUE TITLE
Key is null

### ISSUE THREAD

**Issue by MartinX3** [edenhill/kafkacat#126]
I write a file on the kafka bus
When I read it from the kafka bus, i get the right value, but the key is null

is there a way to add the key to the file?

I would prefer to write a key value array in a json file, which write a message for every array entry with the right key on the bus
(To get rid of the many message files)

**Comment by edenhill** [comment]
You can use `-k ..` to provide a fixed key for all messages produced:
https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L946

**Comment by MartinX3** [comment]
@edenhill 
Is there any example for a seperate key each message?

I can't find an example for a key parameter and it ignores the Key delimitter : provided by -K: in my file.

**Comment by edenhill** [comment]
@MartinX3 How are you calling kafkacat?

**Comment by MartinX3** [comment]
From bash, without GUI as dockercontainer im our company kubernetes cluster :)

**Comment by edenhill** [comment]
Can you provide your exact command line and arguments?

Den tors 13 dec. 2018 21:40 skrev Martin Dünkelmann <
notifications@github.com>:

**Comment by MartinX3** [comment]
Of course

I thought I would need -K:
and key:value in my json file

And I searched for a parameter.
-k key file
would be nice as parameter, too.

```
KAFKAHOST="localhost:9092";
KAFKATOPIC_COURSES="courses";
KAFKAPARTITION=0;
FILES=./data/*;

for f in ${FILES}
    do
      echo "Processing $f file...";
       kafkacat -P -b ${KAFKAHOST} -t ${KAFKATOPIC_COURSES} -p ${KAFKAPARTITION} -K: ${f};
    done;
```

```
"6a86cdcd-6ac7-4abd-9266-6c3667e3b9d3":{
    "type": "mytype",
    "action": "myaction",
    "object": {
        "id": "6a86cdcd-6ac7-4abd-9266-6c3667e3b9d3",
        "title": "My Title",
        "code": "mycode",
        "duration": 2,
        "dates": [],
        "priceFS": 1.62E+3,
        "priceOS": 1.32E+3
    }
}
```

**Comment by edenhill** [comment]
When specifying files on the command line the entire file will be used as the message value, the key must be specified with -k, and will not differ between messages.
You could perhaps work around this by massaging the files into single lines (using jq) and then pipe to kafkacat -K:.

E.g., something like:
`(for f in *.json ; do jq --some-option-to-make-single-line  ; done) | kafkacat ... -K:`

**Comment by MartinX3** [comment]
Sadly I can't choose a -K on my own.
jq expects a valid formatted json file.
So a Key Delimiter is impossible.

And I can't use -k in our kubernetes cluster, because the kafkacat 1.3.1 version installed in ubuntu with apt doesn't support it.

**Comment by zzzmaestro** [comment]
I'm having a similar issue.   I've compiled 1.3.1, but I can't get the -k option to actually do anything.

export $KEY="somevalue"
kafkacat -P -b $BROKER_LIST -t $TOPIC -k $KEY /path/to/file.json 
kafkacat -C -b $BROKER_LIST -t $TOPIC -J -e -q
All Values show: "key":null,

**Comment by MartinX3** [comment]
@zzzmaestro you need 1.4.0

**Comment by zzzmaestro** [comment]
Yesterday, I did a git clone of the master branch and compiled it on RHEL7 and it compiled to 1.3.1.    That’s where I’m confused.

**Comment by MartinX3** [comment]
@zzzmaestro
maybe it's still installed as system app from a repository
I just executed `make`

**Comment by zzzmaestro** [comment]
Not a yum or rpm install.  I had to build it.  I’ve tried both routes:  make and the bootstrap.  I get 1.3.1 with both.

**Comment by MartinX3** [comment]
@edenhill  ? :)

**Comment by nick-demianchuk** [comment]
You can use this patch over master branch to make -k (fixed key) work when produce one message per file content

https://gist.github.com/nick-demianchuk/099148e83a8b0f9a56ac674acb26e2de

**Comment by oemergenc** [comment]
Im am still having problems with this.
```
kafkacat -P -b $BROKER_LIST -t $TOPIC -k $KEY /path/to/file.json
```
Does not seem to work while

```
kafkacat -P -b $BROKER_LIST -t $TOPIC -k $KEY
foo
foooo
```
Seems to work. Im am on version 1.4.0 installed by homebrew.

Any hints on this?

**Comment by edenhill** [comment]
As mentioned in the usage, specifying a file on the command line will treat the entire file as a single message value.
You might want to look at the `-l` option.
