### ISSUE TITLE
build is not working on alpine

### ISSUE THREAD

**Issue by GolanBarkan** [edenhill/kafkacat#128]
Hi,

Im trying to build this project inside docker alpine container and i get this error 

gcc -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align  -I../src rdkafka_example.c -o rdkafka_example  \
        ../src/librdkafka.a -lpthread -L/lib -lz   -lcrypto   -lssl   -lrt -ldl
../src/librdkafka.a(tinycthread.o): In function `thrd_setname':
/tmp-bootstrap/librdkafka/src/tinycthread.c:806: undefined reference to `pthread_setname_np'
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'rdkafka_example' failed
make[1]: *** [rdkafka_example] Error 1
make[1]: Leaving directory '/tmp-bootstrap/librdkafka/examples'
Makefile:38: recipe for target 'examples' failed
make: *** [examples] Error 2
Build of librdkafka FAILED!
Failed to build librdkafka: bootstrap failed
 any idea ?

**Comment by edenhill** [comment]
I  have a fix for this, will push soon.
