### ISSUE TITLE
Is there a way to emulate org.apache.kafka.clients.producer.internals.DefaultPartitioner

### ISSUE THREAD

**Issue by cecchisandrone** [edenhill/kafkacat#131]
Hello,

I was wondering if there is a way to mimic the same behavior of Kafka [default partitioner](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/internals/DefaultPartitioner.java) for producers that is:
1. If a partition is specified in the record, use it
2. If no partition is specified but a key is present choose a partition based on a hash of the key
3. If no partition or key is present choose a partition in a round-robin fashion

I have seen only a way to specify a partition or use a random one.

**Comment by edenhill** [comment]
Yes, librdkafka master (and the upcoming 0.11.4 release) provides a murmur2_random partitioner which is compatible with the Java partitioner.
Use it by setting `-X topic.partitioner=murmur2_random`
