### ISSUE TITLE
kafkacat: symbol lookup error

### ISSUE THREAD

**Issue by GerScau** [edenhill/kafkacat#135]
env: ubuntu 14.04 TLS
        kafkacat-1.3.1
        librdkafka v0.11.4

start kafka getting error message:
kafkacat: symbol lookup error: kafkacat: undefined symbol: rd_kafka_conf_set_log_cb

**Comment by edenhill** [comment]
That looks like you have an older version of librdkafka installed too, and that one is being picked up at link time.

`sudo apt-get purge librdkafka1 librdkafka-dev`  should fix it

**Comment by GerScau** [comment]
it's ok now, thank you!
