### ISSUE TITLE
I want to know what group id kafkacat consumer uses? Also does kafkacat commit after consuming messages?

### ISSUE THREAD

**Issue by hussaintamboli** [edenhill/kafkacat#139]
I searched for this and couldn't find answers. I am investigating missing messages from consumer of my application https://stackoverflow.com/questions/49918484/python-kafka-consumer-missing-to-poll-some-messages

As the above question says, I use Python's Kafka Consumer in my code but I occasionally use below kafkacat command to consume

`kafkacat -C -b <my-broker-ip> -X broker.version.fallback=0.8.2.1 -t <my-topic-name> -o beginning`

and 

`kafkacat -C -b <my-broker-ip> -X broker.version.fallback=0.8.2.1 -t <my-topic-name> -o 10`

**Comment by edenhill** [comment]
kafkacat uses the low level consumer without group coordination when using the `-C` consumer mode, so there is no group.id used then.

**Comment by hussaintamboli** [comment]
Thanks for clarifying. In your experience, have you ever encountered https://stackoverflow.com/questions/49918484/python-kafka-consumer-missing-to-poll-some-messages such issue?

**Comment by peetasan** [comment]
Documentations says that you can use `  -G <group-id>      Mode: High-level KafkaConsumer (Kafka 0.9 balanced consumer groups)`

However when I use this option I still can't see the consumer group.

**Comment by helpermethod** [comment]
@peetasan You need to

    kafkacat -G <groupid> <topic1> <topic2>

i.e. the `group-id` needs to be followed by a list of topics to consume from.
