### ISSUE TITLE
-X param with tild value is not working

### ISSUE THREAD

**Issue by Frantch** [edenhill/kafkacat#141]
Hello,

I'm trying to use this command

`kafkacat -C -b localhost:9095 -t my-topic -X security.protocol=ssl -X ssl.key.location=~/.my_key.key -X ssl.ca.location=~/.full-chain.pem`

I get

`%3|1526991386.875|SSL|rdkafka#consumer-1| [thrd:app]: bss_file.c:175: error:02001002:system library:fopen:No such file or directory: fopen('~/.full-chain.pem','r')`

If I use the full path it works fine

**Comment by edenhill** [comment]
~ is expanded by the shell, and I guess it has some rules when and when not to expand it, this being one of the latter cases.

**Comment by edenhill** [comment]
You can use $HOME instead
