### ISSUE TITLE
Question: How to filter messages in consumer mode

### ISSUE THREAD

**Issue by naxhh** [edenhill/kafkacat#143]
Hi. I've been playing a bit with producing some messages and consuming them.

My main use case is to copy messages from one queue to another (the tool is great for that)
Quick debug some queues: does exists the message with the id X? There is any user with email Y in this queue?

But I fail to see how I can consume a full topic and only print messages given a condition.

Example:
I produce the messages:
hi
hello
hio

And I consume the topic trying to only display the messages that contain hi.
Producing:
hi
hio

If that can be also used with -f that would be awesome.

**Comment by edenhill** [comment]
There is no way to filter messages with kafkacat itself, but you can pipe messages from kafkacat and do the filtering in another program, or using grep, awk, etc, depending on what the message delimiter is.

**Comment by naxhh** [comment]
Hi, thanks for your time. Maybe I'm asking something very stupid but I'm not able to do what you say

I tried with and without `-J`

Here's the normal output:

```
-t "test.Motor.Kafkacat" -q -C -J
{"topic":"test.Motor.Kafkacat","partition":4,"offset":0,"key":"","payload":"{\"asd\":1}"}
{"topic":"test.Motor.Kafkacat","partition":3,"offset":0,"key":"","payload":"{\"asd\": 1}"}
{"topic":"test.Motor.Kafkacat","partition":3,"offset":1,"key":"","payload":"hi"}
{"topic":"test.Motor.Kafkacat","partition":2,"offset":0,"key":"","payload":"{\"asd\":1}"}
{"topic":"test.Motor.Kafkacat","partition":2,"offset":1,"key":"","payload":"tast"}
{"topic":"test.Motor.Kafkacat","partition":2,"offset":2,"key":"","payload":"t"}
{"topic":"test.Motor.Kafkacat","partition":0,"offset":0,"key":"","payload":"hello"}
{"topic":"test.Motor.Kafkacat","partition":0,"offset":1,"key":"","payload":"how are you"}
{"topic":"test.Motor.Kafkacat","partition":0,"offset":2,"key":"","payload":"test"}
{"topic":"test.Motor.Kafkacat","partition":5,"offset":0,"key":"","payload":"test"}
{"topic":"test.Motor.Kafkacat","partition":0,"offset":3,"key":"","payload":"{\"hi\":1}"}
{"topic":"test.Motor.Kafkacat","partition":5,"offset":1,"key":"","payload":"{\"hello\":1}"}
{"topic":"test.Motor.Kafkacat","partition":2,"offset":3,"key":"","payload":"{}"}
{"topic":"test.Motor.Kafkacat","partition":2,"offset":4,"key":"","payload":"{\"t\": 1}"}
```

With jq or grep I get nothing:

```
(herbie) ignacio.tolstoy in ~/code/devops-mt--herbie (try-opsdroid) $ kafkacat -b kafka.global-pre.spain.schibsted.io:9092 -t "test.Motor.Kafkacat" -q -C -J | jq '.'
^C
(herbie) ignacio.tolstoy in ~/code/devops-mt--herbie (try-opsdroid) $ kafkacat -b kafka.global-pre.spain.schibsted.io:9092 -t "test.Motor.Kafkacat" -q -C -J | grep partition
^C
```

What i'm doing wrong?

**Comment by edenhill** [comment]
you can use ` kafkacat .. | tee dbg.log | grep partition` and look at dbg.log to see what data grep is actually seeing.

**Comment by eserte** [comment]
> There is no way to filter messages with kafkacat itself, but you can pipe messages from kafkacat and do the filtering in another program, or using grep, awk, etc, depending on what the message delimiter is.

This works, but it seems that docker is rather inefficient at passing the container's stdout to the host's stdout. Just try something producing much output (e.g. `docker run --entrypoint yes debian:buster > /dev/null` or so) --- this will make dockerd occupy at least one CPU on your machine. Filtering *inside* the container would be much more efficient.

**Comment by edenhill** [comment]
That should also be possible given your filtering tool is available in the docker image.

**Comment by eserte** [comment]
Unfortunately it is not possible to override ENTRYPOINT with a complex sh line. Something like this
```
docker run --network=host --rm --entrypoint='kafkacat ... | grep searchtext' edenhill/kafkacat:1.6.0
```
(or variations using explicit "sh -c") does not work.

The only workaround I know is to create an own Dockerfile like this:
```
FROM edenhill/kafkacat:1.6.0
ENTRYPOINT kafkacat ... | grep searchtext
```
Which is somewhat cumbersome.

**Comment by ivan-skachkov-softwerk** [comment]
In my case the
```
-u                 Unbuffered output
```
flag made the difference. (and thanks for the "| tee ..." tip 👍).

**Comment by ocon0178** [comment]
> In my case the
> 
> ```
> -u                 Unbuffered output
> ```
> 
> flag made the difference. (and thanks for the "| tee ..." tip 👍).

same!
