### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by JeanMertz** [edenhill/kafkacat#145]
I wanted to fetch message headers, but couldn't see it in the help output. Then I found out it was already [implemented last year](https://github.com/edenhill/kafkacat/commit/890539088b4972bd6ab8d4bdeb325f071d35b3f7), and [fixed in January of this year](https://github.com/edenhill/kafkacat/issues/129), but the latest stable release is from April of last year.

I can build from source, but since the last release, librdkafka v0.11.0 to v0.11.4 have been released, so I reckon there are a lot of fixes and changes that might be useful to anyone using the latest stable version.

**Comment by pimpelsang** [comment]
Yes, would like to use -F to load configuration from file, but with build from brew doesn't work. Building  each from source each time is not so cool

**Comment by jochenchrist** [comment]
+1 for a new Release (with Homebrew).
Currently is 1.3.1 (April 2017).

Especially for header support.

**Comment by edenhill** [comment]
I'll try to get a release out this week, thanks for your patience

**Comment by MartinX3** [comment]
Is there an ETA for the release? :)
I can't use the -k because the 1.3.1 hasn't this feature. :)
I need it in our kubernetes cluster, where a ubuntu docker image installs kafkacat with apt.

**Comment by edenhill** [comment]
Kafkacat v1.4 will be released with librdkafka v1.0.0 is released, which is later this week hopefully.

**Comment by MartinX3** [comment]
https://github.com/edenhill/librdkafka/issues/2172

**Comment by matthewbyrne** [comment]
Now that librdkafka 1.0.0 is released, can kafkacat be up updated?

https://github.com/edenhill/librdkafka/releases/tag/v1.0.0

**Comment by edenhill** [comment]
v1.4.0 released
