### ISSUE TITLE
Connect to Heroku Kafka: ssl.ca.location failed

### ISSUE THREAD

**Issue by brianlow** [edenhill/kafkacat#146]
Has anyone been able to connect to Kafka hosted on Heroku?

```
$ kafkacat -C -t $TOPIC -b $KAFKA_URL -X security.protocol=ssl -X ssl.key.location=<(echo $KAFKA_CLIENT_CERT_KEY) -X ssl.certificate.location=<(echo $KAFKA_CLIENT_CERT) -X ssl.ca.location=<(echo $KAFKA_TRUSTED_CERT)
% ERROR: Failed to create producer: ssl.ca.location failed: No error
```

Based on [these instructions](https://gist.github.com/crcastle/cb21c2148fc57ad89753bf28b561d910).

I am able to connect using a custom Elixir client (kafka_ex) so it isn't a networking issue. However the elixir client doesn't require the ssl.ca.location so it must not be validating the server's cert.

**Comment by edenhill** [comment]
Make sure to specify the *path* of the certs and keys, and not their contents.

**Comment by brianlow** [comment]
:+1: Thanks. Got it working on a shared Kafka. Unable to connect to Kafka in a Private Space but that could be a networking issue.
