### ISSUE TITLE
Kafka Headers support

### ISSUE THREAD

**Issue by urgupluoglu** [edenhill/kafkacat#148]
It looks like kafka header support added a while ago, but there is no example how to use it in command line. Can you give me an example how to push data (as producer) with custom headers?
p.s. I already tried -h and -H, but no luck.

**Comment by edenhill** [comment]
fixed on master

**Comment by briansorahan** [comment]
@edenhill When will this be released?

I'm on mac

```
brew info kafkacat
kafkacat: stable 1.3.1 (bottled)
Generic command-line non-JVM Apache Kafka producer and consumer
https://github.com/edenhill/kafkacat
/usr/local/Cellar/kafkacat/1.3.1_1 (5 files, 51.4KB) *
  Poured from bottle on 2019-03-07 at 10:59:50
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/kafkacat.rb
==> Dependencies
Required: librdkafka ✔, yajl ✔
==> Analytics
install: 1,025 (30 days), 2,606 (90 days), 10,089 (365 days)
install_on_request: 1,023 (30 days), 2,599 (90 days), 9,951 (365 days)
build_error: 0 (30 days)
```

But `kafkacat -h` doesn't show any info about the header support documented in the readme.

**Comment by edenhill** [comment]
Shortly after librdkafka v1.0.0 is released, which is within the next two weeks.

**Comment by tunix** [comment]
@edenhill Hi! Looks like it's been released. Will there be a release of kafkacat that includes this change?

**Comment by edenhill** [comment]
It is in v1.4.0
https://github.com/edenhill/kafkacat/releases/tag/1.4.0

**Comment by tunix** [comment]
@edenhill Sorry my mistake 🙂 I meant the Docker image. I don't know if it has anything to do with your work but the confluentinc/cp-kafkacat image doesn't have this feature.

**Comment by edenhill** [comment]
ping @ybyzek

**Comment by briansorahan** [comment]
Looks like cp-kafkacat:5.3.0 is using the debian/1.3.1-1 release.
@ybyzek Any idea when we'll get header support in cp-kafkacat?
We're starting to adopt headers at my company and kafkacat is a crucial tool for my team. We prefer to use the dockerized version since it's easier to install.
Would reeeeally love to see header support in the docker image.

**Comment by edenhill** [comment]
Use `edenhill-kafkacat:20190711`, it comes with headers, Avro and Schema-registry support.

**Comment by briansorahan** [comment]
IMO this image is also an improvement because `ENTRYPOINT ["kafkacat"]`

It's redundant to say
```
docker run confluentinc/cp-kafkacat kafkacat OPTIONS
```
