### ISSUE TITLE
Issue setting topic config options (in the global scope)

### ISSUE THREAD

**Issue by ctrochalakis** [edenhill/kafkacat#149]
Hello Magnus,

When running

`kafkacat -b kafka1 -X request.required.acks=all -t mytopic`

The acks are not enabled as expected(?), this in fact happens for all topic config options. The way to bypass this is to specify it as a topic option prepending  `topic.`:

`kafkacat -b kafka1 -X topic.request.required.acks=all -t mytopic`

This is because `rkt_conf (topic conf)` overrides `rk_conf` in `rd_kafka_topic_new()`. I am wondering if having an explicit `rkt_conf` is actually needed. Perhaps using a single `rk_conf` and its internal default_topic_conf is enough, in that case we should handle `topic.` prefixed options accordingly for backwards compatibility.

If this is indeed the case I could work on a patch.

**Comment by edenhill** [comment]
Yes you are right and your solution sounds good.
Please submit a PR :)

**Comment by edenhill** [comment]
Fixed on master
