### ISSUE TITLE
Exit successfully when last message received not working (from source)

### ISSUE THREAD

**Issue by dharrigan** [edenhill/kafkacat#163]
Hi,

Just cloned master and built (using `bootstrap.sh`):

```
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2017, Magnus Edenhill
Version 1.3.1-64-gd82aac (librdkafka 1.0.0-pre2 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_plain,sasl_scram,plugins)
```

Issuing the following:

```
kafkacat -qCb kafka01 -t uat_messages -o beginning -e
```

No longer exits, instead kafkacat sits waiting for the next message to arrive.

In the currently released version

```
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2015, Magnus Edenhill
Version 1.3.1 (JSON) (librdkafka 0.11.3 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins)
```

the `-e` flag works as expected - when the last message is consumed, kafkacat exits to the shell.

**Comment by edenhill** [comment]
librdkafka master changed the default of enable.partition.eof to false, but kafkacat hasn't caught up just yet. The workaround for now is to provide `-X enable.partition.eof=true`

**Comment by edenhill** [comment]
Fixed on kafkacat master

**Comment by dharrigan** [comment]
Thank you! :-)
