### ISSUE TITLE
How to disable "% Reached end of topic..." message?

### ISSUE THREAD

**Issue by gunnarmorling** [edenhill/kafkacat#168]
Probably that's a bit of a noob question, but is there a way to suppress that message when reaching the end of a topic? This breaks things when piping output to jq. I'm using 1.4.0-RC1 and I didn't observe this with 1.3.1 before. Any help would be welcomed!

**Comment by edenhill** [comment]
It shouldnt break anything since it is emitted to stderr (and thus not piped).
But you can make kafkacat more silent by passing `-q`

**Comment by gunnarmorling** [comment]
Thanks for the quick reply!

> It shouldnt break anything since it is emitted to stderr (and thus not piped).

Hum, for some reason it did; I ran

    kafkacat -b kafka:9092 -C -o beginning -t Customer | jq .
    ... // messages properly shown; and then:
    parse error: Invalid numeric literal at line 5, column 2

But appending -q did the trick indeed. Thanks!

**Comment by edenhill** [comment]
That must be something else, the EOF printout is emitted on stderr which is not piped to jq

**Comment by mmerdes** [comment]
thanks for the hint!
(had the same issue when piping into visidata)
