### ISSUE TITLE
ERROR: Failed to acquire metadata: Local: Broker transport failure

### ISSUE THREAD

**Issue by bismoy2013** [edenhill/kafkacat#169]
Bismoys-MacBook-Air:portwork bismoy$ kubectl get services
    NAME         TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)                                        AGE
    kaf1         LoadBalancer   10.101.123.17    172.31.25.198   9092:31883/TCP                                 8m59s
    kaf2         LoadBalancer   10.100.183.176   172.31.26.5     9092:30955/TCP                                 8m59s
    kubernetes   ClusterIP      10.96.0.1        <none>          443/TCP                                        21m
    zoo1         LoadBalancer   10.103.102.136   <pending>       
    2181:31025/TCP,2888:30933/TCP,3888:31229/TCP   16m
    zoo2         LoadBalancer   10.106.93.113    <pending>       
    2181:31456/TCP,2888:30805/TCP,3888:31614/TCP   16m

Was trying to set up while following this tutorial 
     https://medium.com/@itseranga/kafka-zookeeper-cluster-on-kubernetes-43a4aaf27dbb

Error I am getting :
```
Command in terminal - 
    kafkacat -L -b 172.31.25.198:9092
Error -
 % ERROR: Failed to acquire metadata: Local: Broker transport failure

**Comment by edenhill** [comment]
That is usually an indication that the client is unable to connect (at all, or within kafkacat's 5s metadata timeout) to the broker.
Try adding `-d broker` to see if it connects at all.

**Comment by bismoy2013** [comment]
You mean ```kafkacat -L -b 172.31.25.198:9092 -d broker``` ? or ```kafkacat -L -d 172.31.25.198:9092```

**Comment by bismoy2013** [comment]
This is what I got 

```
Bismoys-MacBook-Air:portwork bismoy$ kafkacat -L -b 172.31.25.198:9092 -d broker
%7|1550506722.903|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1550506722.903|BROKER|rdkafka#producer-1| [thrd:app]: 172.31.25.198:9092/bootstrap: Added new broker with NodeId -1
%7|1550506722.903|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1550506722.903|BRKMAIN|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: Enter main broker thread
%7|1550506722.903|CONNECT|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: broker in state INIT connecting
%7|1550506722.903|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v0.11.6 (0xb06ff) rdkafka#producer-1 initialized (builtin.features 0xffff, debug 0x2)
%7|1550506722.903|CONNECT|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: Connecting to ipv4#172.31.25.198:9092 (plaintext) with socket 7
%7|1550506722.904|STATE|rdkafka#producer-1| [thrd:172.31.25.198:9092/bootstrap]: 172.31.25.198:9092/bootstrap: Broker changed state INIT -> CONNECT
% ERROR: Failed to acquire metadata: Local: Broker transport failure

**Comment by edenhill** [comment]
My guess would be that it the client host can't reach the broker host due to routing or network filtering issues.
You can verify this by:
`ping 172.31.35.198`
and `telnet 172.31.35.198 9092`

**Comment by bismoy2013** [comment]
you are right , it's unable to reach the broker host , what should I do in this scenario ? any advice ?

```Bismoys-MacBook-Air:portwork bismoy$ ping 172.31.35.198
PING 172.31.35.198 (172.31.35.198): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6

**Comment by xmariachi** [comment]
It is possible here that ping port is not reachable but broker port is.
Did you solve this issue @bismoy2013 ?

**Comment by bismoy2013** [comment]
Yeah, solved.

**Comment by xmariachi** [comment]
Any word on what was the problem / any solution? Thanks.

**Comment by bismoy2013** [comment]
@xmariachi actually, I wasn't able to ping the server at all , this problem often occurs whenever you are unable to ping or reach the server located remotely .

**Comment by MohammedAliKadri** [comment]
i am seeing errors like this, although my kafka cluster is working.
```

%7|1561101376.914|BROKERFAIL|rdkafka#producer-1| [thrd:172.31.3.95:9092/105]: 172.31.3.95:9092/105: failed: err: Local: Broker handle destroyed:                      (errno: Resource temporarily unavailable)
%7|1561101376.914|STATE|rdkafka#producer-1| [thrd:172.31.3.95:9092/105]: 172.31.3.95:9092/105: Broker changed state UP -> DOWN
%7|1561101376.914|TERMINATE|rdkafka#producer-1| [thrd:172.31.3.159:9092/117]: 172.31.3.159:9092/117: Handle is terminating: failed 0 request(s)                      in retry+outbuf
%7|1561101376.914|BROKERFAIL|rdkafka#producer-1| [thrd:172.31.3.159:9092/117]: 172.31.3.159:9092/117: failed: err: Local: Broker handle destroye                     d: (errno: Resource temporarily unavailable)
%7|1561101376.914|STATE|rdkafka#producer-1| [thrd:172.31.3.159:9092/117]: 172.31.3.159:9092/117: Broker changed state UP -> DOWN
%7|1561101376.914|TERMINATE|rdkafka#producer-1| [thrd:172.31.1.104:9092/114]: 172.31.1.104:9092/114: Handle is terminating: failed 0 request(s)                      in retry+outbuf
```
