### ISSUE TITLE
ERROR: Unsupported formatter: %h

### ISSUE THREAD

**Issue by kpeu3i** [edenhill/kafkacat#173]
I got an error when printing headers in consumer:
```
$ kafkacat -b localhost:9094 -C -t adapter-feed -f 'Headers: %h: Message value: %s\n'
% ERROR: Unsupported formatter: %h
```

**Comment by edenhill** [comment]
%h has not yet been released and is only available on the master branch if you build kafkacat from source.

**Comment by Krandelbord** [comment]
Can You please update this ticket when it will be realesed ?
