### ISSUE TITLE
kafkacat: symbol lookup error: kafkacat: undefined symbol: rd_kafka_topic_partition_list_sort

### ISSUE THREAD

**Issue by DinoStray** [edenhill/kafkacat#174]
OS: Ubuntu 18.04.2 LTS
apt-get install kafkacat
apt-get install librdkafka-dev libyajl-dev

while I run 
`kafkacat -b localhost:14061 -L -J`
Some error occured:
kafkacat: symbol lookup error: kafkacat: undefined symbol: rd_kafka_topic_partition_list_sort

**Comment by edenhill** [comment]
You need to upgrade your librdkafka version, get the latest from the confluent apt repositories:
https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#systemd-ubuntu-debian-install
