### ISSUE TITLE
% ERROR: Failed to produce message (275 bytes): Success

### ISSUE THREAD

**Issue by champtar** [edenhill/kafkacat#175]
I just upgraded from librdkafka 0.11.6 / kafkacat 1.3.1 to librdkafka 1.0.0 / kafkacat 1.4.0
```
/usr/bin/socat -u tcp4-listen:5515,fork "exec:/usr/bin/kafkacat -P -E -X compression.codec=lz4 -X queue.buffering.max.ms=100 -X api.version.fallback.ms=0 -X broker.version.fallback=0.11.0 -X security.protocol=sasl_plaintext -X sasl.mechanisms=PLAIN -X sasl.username=kafkacat -X sasl.password='aaaa' -b 192.168.1.2 -t mytopic"
```
I was able to send tons of traffic, and now I get
```% ERROR: Failed to produce message (275 bytes): Success```
and kafkacat exit despite the '-E'

https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L185
I don't understand why rd_kafka_producev() return != 0 and rd_kafka_last_error() return 0

**Comment by edenhill** [comment]
Ouch, thanks for catching this.

The last_error() line shouldn't be there, it overwrites the actual error return from producev().

**Comment by champtar** [comment]
Thanks !!

**Comment by TylerLubeck** [comment]
Hey, sorry to be needy - any chance we can get a point release with this?
