### ISSUE TITLE
Is `--interactive` required when running in docker?

### ISSUE THREAD

**Issue by alexhumphreys** [edenhill/kafkacat#176]
I'm trying to run this `kafkacat` on kubernetes. The run command looks like the following:

```
kubectl run --generator=run-pod/v1 \
  --restart=Never \
  --image-pull-policy=Always \
  --env="KAFKA_HOST=kafka" \
  --env="KAFKA_PORT=9092" \
  --env="KAFKA_TOPIC=some-topic" \
  --command=true \
  kafka-backup --image confluentinc/cp-kafkacat -- bash -c "kafkacat -v -o beginning -e -q -b \$KAFKA_HOST:\$KAFKA_PORT -t \$KAFKA_TOPIC > /tmp/foo.txt ; ls -lah /tmp/foo.txt"
```

The output of that `ls` command shows that the file is empty:

`-rw-r--r--. 1 root root 0 Apr 17 09:38 /tmp/foo.txt`

However, if I add the flags  `--attach=true -it` to the above run command then the `ls` command shows that the file has been populated as expected:

`-rw-r--r--. 1 root root 34K Apr 17 09:38 /tmp/foo.txt`

(Also the command hung and I had to exit with CTRL+C, but that's a different story)

Now normally I'd use the `--attach=true -it` flags as a workaround and all would be good, but I'm trying to run this as a kubernetes cron job, so I wouldn't be able to pass those flags.

When running as a cron job I see the same empty file behaviour. When I `kubectl exec` into the pod created by the cron job and run the `kafkacat` command myself then the file gets populated, so it seems to be related to whether it is interactive or not, rather than a configuration issue.

I notice in the README the `docker run` command has the `--tty --interactive` flags passed too.

So I'm wondering, is it possible to use `kafkcat` in docker without it being in interactive?

Is there any work around for this, like some other way to write the output to a file rather than a bash `>` redirect? Or maybe I've misunderstood something about how `kafkacat` works?

Any assistance would be great :)

**Comment by edenhill** [comment]
If you don't specify a mode, -P, -C, etc, kafkacat will try to check the type of input and output file descriptors, if input is a tty it uses consumer mode, otherwise producer:
https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L1628

I'm guessing you don't get a tty unless you pass -t to docker, and since you're not explicitly specifying a mode to kafkacat you will get a producer that does not produce any messages, rather than the consumer you want.

The fix is to add `-C` or `-G mygrp` to the kafkacat command line, depending on which type of consumer you want.

**Comment by alexhumphreys** [comment]
Thanks for the fast reply, that `-C` flag was just what I needed. 

Adding `-C` made it consume, though then it failed to exit even with the `-e` flag. This could be related to this issue here: #86. Downgrading to docker image `confluentinc/cp-kafkacat:5.0.0` fixed the issue.

But that's unrelated to my original question, so I'll close this issue. Thanks again!

**Comment by ClarenceL** [comment]
+1 for sure, I was pulling my hair out due to this, I was running kafkacat for Gitlab CI tests and couldn't use tty

**Comment by ClarenceL** [comment]
> If you don't specify a mode, -P, -C, etc, kafkacat will try to check the type of input and output file descriptors, if input is a tty it uses consumer mode, otherwise producer: https://github.com/edenhill/kafkacat/blob/master/kafkacat.c#L1628
> 
> I'm guessing you don't get a tty unless you pass -t to docker, and since you're not explicitly specifying a mode to kafkacat you will get a producer that does not produce any messages, rather than the consumer you want.
> 
> The fix is to add `-C` or `-G mygrp` to the kafkacat command line, depending on which type of consumer you want.

Please add this somewhere in the README!
