### ISSUE TITLE
Debian release

### ISSUE THREAD

**Issue by padilo** [edenhill/kafkacat#183]
The current version on debian packages is 1.3.1.
Can you do the release of the 1.4.0?

**Comment by edenhill** [comment]
I'm not the maintainer of the Debian package, @vincentbernat is

**Comment by vincentbernat** [comment]
It depends if you need an update of the GitHub repository or if you want a proper release inside Debian. In the later case, Debian is currently in deep freeze until mid-July, so it's not possible.

**Comment by edenhill** [comment]
@vincentbernat An upcoming issue is that when #151 is merged kafkacat will depend on libserdes to get schema-registry support. This is optional of course, but a much desired feature.
Not sure how that'll be handled in Debian.

**Comment by vincentbernat** [comment]
As it's not present in Debian, I suppose we will just compile without Avro support.
