### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [edenhill/kafkacat#187]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [fmt_add](https://github.com/edenhill/kafkacat/blob/be0cfa615b4e854f8b3b437fd80f53bd72c111a3/format.c#L46)
- [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [metadata_print](https://github.com/edenhill/kafkacat/blob/05b052cf861b60aaba488716a4ed9af47497a544/kafkacat.c#L770)

**Comment by edenhill** [comment]
Unless someone tries to provoke a crash, there is no risk of malloc failing in fmt_add() for any decent input size.

As for printf() in metadata_print(), I'm not sure what should be fixed?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by edenhill** [comment]
The ignoring of the return values is intentional; there is nothing meaningful we can do in the unlikely event that printf() fails.

**Comment by elfring** [comment]
I find that there are [usual software design options to consider for complete exception handling](https://wiki.sei.cmu.edu/confluence/display/c/ERR00-C.+Adopt+and+implement+a+consistent+and+comprehensive+error-handling+policy "Adopt and implement a consistent and comprehensive error-handling policy.").

**Comment by edenhill** [comment]
Feel free to suggest/provide specific improvements.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* Would you like to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?
