### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [edenhill/kafkacat#188]
[The variable “`run`”](https://github.com/edenhill/kafkacat/blob/72c86ec04f27b349b0888890613d7ee23728abfa/kafkacat.h#L75 "Update candidate") should [use the data type “`sig_atomic_t`”](https://wiki.sei.cmu.edu/confluence/display/c/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Description for signal handling").

**Comment by edenhill** [comment]
This is good advice, though I don't think it matters much in kafkacat, but feel free to submit a PR.
