### ISSUE TITLE
Read from beginning with -G

### ISSUE THREAD

**Issue by HungUnicorn** [edenhill/kafkacat#191]
I found -C is not supported in 1.4.0 and also the docker image https://hub.docker.com/r/edenhill/kafkacat/tags , tag:20190709

I use -G but don't find a way to set the offset to earliest, -o is not working when using together with -G, or?
```
High-level KafkaConsumer mode:
  kafkacat -b <broker> -G <group-id> topic1 top2 ^aregex\d+
```

**Comment by edenhill** [comment]
`kafkacat -b $BROKERS -C -t $TOPIC -o beginning`, you can even skip the `-C`

**Comment by edenhill** [comment]
`-o beginning` works with -G as well, but will only be used if there are no previous commits for this topic,partition,group combo

**Comment by HungUnicorn** [comment]
hmm strange. my command:
```
         docker run --tty --interactive --rm --net=host\
>                  edenhill/kafkacat:20190709 \
>                  kafkacat -b localhost:29092 -C -t kafkacat -o beginning \
>   -f '\n Value (%S bytes): %s Headers: %h\n' 
Error: file/topic list only allowed in producer(-P)/kafkaconsumer(-G) mode

**Comment by edenhill** [comment]
You probably need to provide additional quotes for -f since the bash-in-docker will expand those to separate arguments, try:
```
docker run --tty --interactive --rm --net=host \
                  edenhill/kafkacat:20190709 \
                  kafkacat -b localhost:29092 -t kafkacat -o beginning \
   -f '"\n Value (%S bytes): %s Headers: %h\n"' 
```

**Comment by edenhill** [comment]
Second thought, you shouldn't specify "kafkacat" after the docker image, that is already the entry point. So try:
```
docker run --tty --interactive --rm --net=host \
                  edenhill/kafkacat:20190709 \
                  -b localhost:29092 -t kafkacat -o beginning \
   -f '\n Value (%S bytes): %s Headers: %h\n' 
```

**Comment by HungUnicorn** [comment]
it works!! thank you

**Comment by martinjtlive** [comment]
Dear Magnus,
Really appreciate this repository. Thank you. I am novice a developer. You could say barely novice. Nevertheless, I was able to download this repository and msbuild it. I can get the producer working with key and headers. However, I struggle print the headers in the consumer window. I dont have docker with me. 

So here is how I wrote the producer:
C:\workspace\kafkacat\win32\x64\Debug>kcat -P -b localhost:9092 -t MTM -K : -H appName=kcat -H appId=1
123: Hello
123: Hel
123: Hel
123: He
123: H
13: H

In my consumer CLI, I get error: 
C:\workspace\kafkacat\win32\x64\Debug>kcat -b localhost:9092 -t MTM -C -f '%k - %s - %h'
Error: file/topic list only allowed in producer(-P)/kafkaconsumer(-G) mode

Am I doing something wrong? Please advise good sir

**Comment by martinjtlive** [comment]
Dearest Magnus, thank you good sir :-) I very much appreciate your help here and thank you for the great work of this and other repositories. 

Your advise works!!!!!!

See below:
C:\workspace\kafkacat\win32\x64\Debug>kcat -b localhost:9092 -t MTM -C -f key:%k\tmessage:%s\theader:%h\n
key:Justy       message:Hellotest123    header:headerkey=headervalue
key:Justy       message:Hellotest123456 header:headerkey=headervalue
key:Test        message: HelloFromKcat  header:appName=kcat,appId=1
key:Test        message: HelloFromK     header:appName=kcat,appId=1
key:Test        message: HelloFrom      header:appName=kcat,appId=1
key:Test        message: Hello  header:appName=kcat,appId=1
key:Test        message: H      header:appName=kcat,appId=1
key:Tt  message: H      header:appName=kcat,appId=1
key:123 message: Hello  header:appName=kcat,appId=1
key:123 message: Hel    header:appName=kcat,appId=1
key:123 message: Hel    header:appName=kcat,appId=1
key:123 message: He     header:appName=kcat,appId=1
key:123 message: H      header:appName=kcat,appId=1
key:13  message: H      header:appName=kcat,appId=1
% Reached end of topic MTM [0] at offset 14

Sincerely,
Martin
self learning developer, sometimes clumsy
