### ISSUE TITLE
Put version number / link to current version in README

### ISSUE THREAD

**Issue by 1jerry** [edenhill/kafkacat#192]
I was delighted to find your tool for testing my Kafka topics using ARVO, but the options for using ARVO (-s) do not work on any current release I can use.  (1.4.0 from brew, or 1.3.1-1 from Docker).  From this I assume your README is documenting features that are not released (packaged, built) yet.

While I appreciate the amount of work that goes into making a release, I would find it very helpful in the README file that 1) you reference the version of the program that has the documented features, and 2) have a link to the _released_ version's documentation.

On a related note, how can I be notified when brew is updated with the version that uses ARVO schemas?

Thanks.

**Comment by edenhill** [comment]
https://github.com/edenhill/kafkacat/releases

**Comment by edenhill** [comment]
The README on github master branch will always reflect the current development state of kafkacat - i.e., what (probably) goes in the next version of kafkacat, not the latest release, use the release page for that information.

**Comment by 1jerry** [comment]
Having nothing to do with the quality or usefulness of this program, I have a suggestion.
If you are going to document features that are not available and/or have not worked for 5 months on README on master, it would be great if you say somewhere that the feature isn't available yet.  A link to the _real_ documentation for what the program can _currently_ do would be nice too.  :)
