### ISSUE TITLE
compression type "zstd" is not supported

### ISSUE THREAD

**Issue by eranmiz132** [edenhill/kafkacat#195]
"zstd" (ZStandard) is not supported as a compression type,
only snappy, gzip, lz4.

see file: kafkacat.c

**Comment by edenhill** [comment]
Either your librdkafka is outdated or it was not built with zstd support (missing libzstd-dev package on the system).

**Comment by eranmiz132** [comment]
i tried the latest docker image confluentinc/cp-kafkacat:5.3.0-1, and got:
% ERROR: Invalid value "zstd" for configuration property "compression.codec"

Also, the source code, imply that "zstd" is not supported:
https://github.com/edenhill/kafkacat/blob/master/kafkacat.c

**Comment by edenhill** [comment]
try `edenhill/kafkacat:20190711`

**Comment by thebearmayor** [comment]
Hm, I'm having the same problem building from source on Amazon Linux. I installed `libzstd-devel` on the build system. Then on my client system, using the new built kafkacat, I got this error.
```kafkacat: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory```

So, I installed `libzstd` on the client system, and then got the original error again.
```% ERROR: Topic <topic> [5] error: Unsupported compression type```

This is how I'm building.
```
yum install -y cyrus-sasl-devel cmake libcurl-devel libzstd-devel
./bootstrap.sh
```

**Comment by edenhill** [comment]
@thebearmayor run `./kafkacat -V` and check if zstd is in the builtin.features list

**Comment by thebearmayor** [comment]
@edenhill It's been suggested that this is dependent on https://github.com/edenhill/librdkafka/pull/2183. So I'll just wait for that to be merged and build again.
```
$ kafkacat -V
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2019, Magnus Edenhill
Version 1.4.0-21-g006b93 (JSON, Avro, librdkafka 1.1.0 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer)
```

**Comment by edenhill** [comment]
That PR will not be merged in the short term, so I suggest you employ the workaround by reverting broker-side topic configuration compression.type to producer (default).

**Comment by thebearmayor** [comment]
Thanks for the workaround, I'll give it a go.
