### ISSUE TITLE
JSON usage printed without ENABLE_JSON?

### ISSUE THREAD

**Issue by ankon** [edenhill/kafkacat#199]
While reading through kafkacat I noticed this part:
https://github.com/edenhill/kafkacat/blob/3b4bcf00d322533c374e226f2a4eb16501e8a441/kafkacat.c#L1151-L1160

All other places related to JSON are fenced with `#ifdef ENABLE_JSON`, should this be done here as well?

**Comment by edenhill** [comment]
Yes, good catch!
