### ISSUE TITLE
message.timeout.ms is not enforced when producing

### ISSUE THREAD

**Issue by caverman** [edenhill/kafkacat#211]
kafkacat version 1.5 and librdkafka 1.2.2

Running kafkacat:
kafkacat -P -b 10.144.0.2:9092 -X "debug=protocol,broker,topic,msg" -X "message.timeout.ms=1" -t test

I am unable to trigger the message.timeout.ms value. The log mesages I see when I produce a message are as follows:

```
fgh
%7|1575053805.346|PRODUCE|rdkafka#producer-1| [thrd:kafkatestserver:9092/0]: kafkatestserver:9092/0: test [3]: Produce MessageSet with 1 message(s) (71 bytes, ApiVersion 7, MsgVersion 2, MsgId 0, BaseSeq -1, PID{Invalid}, uncompressed)
%7|1575053805.346|SEND|rdkafka#producer-1| [thrd:kafkatestserver:9092/0]: kafkatestserver:9092/0: Sent ProduceRequest (v7, 122 bytes @ 0, CorrId 4)
%7|1575053805.372|RECV|rdkafka#producer-1| [thrd:kafkatestserver:9092/0]: kafkatestserver:9092/0: Received ProduceResponse (v7, 48 bytes, CorrId 4, rtt 26.16ms)
%7|1575053805.372|MSGSET|rdkafka#producer-1| [thrd:kafkatestserver:9092/0]: kafkatestserver:9092/0: test [3]: MessageSet with 1 message(s) (MsgId 0, BaseSeq -1) delivered
```
Based on this I see the ProduceResponse is rtt 26.16ms so greater than the 1 ms timeout, so I would expect a "Local: Message timed out"

I'm aware that the Producer timeout should be set on a per topic basis, but through Kafkacat I'm unaware of how I can configure this. I have also tried adding the configurations to a configuration file and referenced it with -F flag. But the same outcome.

**Comment by edenhill** [comment]
Regardless of message.timeout.ms we allow at least 100ms for each produce request.
