### ISSUE TITLE
Connecting to schema registry 404 not found

### ISSUE THREAD

**Issue by moezg** [edenhill/kafkacat#212]
Hello everybody. 

I am trying to consume a topic with avro serialization and i keep get this error : 
 ERROR: Failed to format message in tpc_alertes.dc05 [2] at offset 623: Avro/Schema-registry message deserialization: REST request failed (code 404): {"error_code":404,"message":"HTTP 404 Not Found javax.ws.rs.NotFoundException: HTTP 404 Not Found\njavax.ws.rs.NotFoundException: HTTP 404 Not Found\n\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:2 : terminating

I'm sure pretty sure my url is good since i get the schema when i try curl https://dev...../schemas/ids/3 
Anyone had this before ? 

Thank you

**Comment by edenhill** [comment]
Since you're not providing your command line arguments it has hard to say, but SR is quite picky without trailing slashes, so make sure it is there, or not there, whichever one it likes.

**Comment by moezg** [comment]
Hello, Thanks for your quick answer . 
This is my command 
kafkacat-1.5 -b "broker_adress" -t "mytopic" -C -s avro -r https://mypath/cp-schema-registry-client/schemas/ids/3
 and this is approximately what i get  when i try curl+ path
{"schema":"{\"type\":\"record\",\"name\":\"test\",\"namespace\":\"test\",\"fields\":[{\"name\":\"operation_date\",\"type\":\"string\",\"doc\":\"yyyy-MM-ddTHH:mm:ss.SSS\"},{\"name\":\"test\",\"type\":\"string\"},{\"name\":\"test\",\"type\":\"long\",\"doc\":\"-1 \"},{\"name\":\"test\",\"type\":\"long\"},{\"name\":\"t\",\"type\":\"string\"},{\"name\":\"test\",\"type\":\"boolean\",\"doc\":\"\"}]}"}

**Comment by moezg** [comment]
I tried kafkacat-1.5 -b "broker_adress" -t "mytopic" -C -s avro -r https://mypath/cp-schema-registry-client/schemas/ids/3 -D \\

**Comment by edenhill** [comment]
You should only specify the base url of the schema-registry, not the full url to the schema.
