### ISSUE TITLE
-b still required even if metadata.broker.list in ~/.config/kafkacat.conf ?

### ISSUE THREAD

**Issue by datamove** [edenhill/kafkacat#213]
Dear Developers,

I came across #85 that asked to have -X override -b, but I wonder, if I have metadata.broker.list property in ~/.config/kafkacat.conf or in $KAFKACAT_CONFIG, why is -b still required? Is it something fundamental or just doesn't work for me?

For reference,  my config look like:

```
$ echo $KAFKACAT_CONFIG
metadata.broker.list=10.0.1.208:6667
$ cat ~/.config/kafkacat.conf 
bootstrap.servers=10.0.1.208:6667
metadata.broker.list=10.0.1.208:6667
```

Thanks in advance!

**Comment by edenhill** [comment]
That sounds like a bug, will look into it.

**Comment by edenhill** [comment]
As a workaround you can use `kafkacat -b , ..`  (i.e., an empty list of brokers)

**Comment by edenhill** [comment]
Not reproducible:
```
$ ./kafkacat -L -m 1 -F kafkacat.config
% Reading configuration from file kafkacat.config
% ERROR: Failed to acquire metadata: Local: Broker transport failure
```

**Comment by mikaello** [comment]
I also got this issue. I am using kafkacat via docker (`alias kafkacat='docker run -i edenhill/kafkacat:1.6.0'`), and I guess that is the problem. Config file is not supported when running kafkacat trough docker? If that is correct, it would be a good idea to add that to the configuration section in the README.

```
D:~ # alias kafkacat='docker run -i edenhill/kafkacat:1.6.0'

D:~ # ll .config/kafkacat.conf
-rw-r--r-- 1 mikaello mikaello 225 aug.   3 15:01 .config/kafkacat.conf

D:~ # kafkacat -C -t $TEST_TOPIC -e -o -2 -F .config/kafkacat.conf
% ERROR: Failed to open .config/kafkacat.conf: No such file or directory

D:~ # kafkacat -C -t $TEST_TOPIC -e -o -2
Error: -b <broker,..> missing

D:~ # kafkacat -C -t $TEST_TOPIC -e -o -2 -b ,
%5|1596460317.093|CONFWARN|rdkafka#consumer-1| [thrd:app]: No `bootstrap.servers` configured: client will not be able to
 connect to Kafka cluster
```

**Comment by edenhill** [comment]
As for the "No such file or directory" problem: the docker container will not be able to access your outer host file system unless you map it through `docker -v ..`.

**Comment by mikaello** [comment]
Thanks for the tip about `-v`. Here are a full example for others looking for the same (getting config file when running with docker):
```shell
docker run -it -v "$PWD"/kafkacat.conf:/root/.config/kafkacat.conf edenhill/kafkacat:1.6.0 -C -t <some_topic_of_broker_defined_in_config>
```
