### ISSUE TITLE
Schema registry URL in configuration file not picked-up before SerDe flags validation

### ISSUE THREAD

**Issue by Perdjesk** [edenhill/kafkacat#220]
# Steps to reproduce

1. Create a configuration file:
```
$ cat kafkacat.conf
schema.registry.url=http://schema-registry-url:8080
metadata.broker.list=mybroker
```
2. Run a kafkacat consumer using the above configuration file and enable avro SerDe
```
docker run -it -v "$PWD"/kafkacat.conf:/root/.config/kafkacat.conf --network=host edenhill/kafkacat:1.5.0 -C -t syslog -s avro
```

# Actual result
```
% ERROR: -r requires -s avro and vice-versa
```

# Expected result
The `-r` flag configuration must be picked-up from configuration file before flags validation.

**Comment by edenhill** [comment]
Fixed on master
