### ISSUE TITLE
Questions about `-o`

### ISSUE THREAD

**Issue by atheken** [edenhill/kafkacat#227]
Hi, thanks for all the work on kafkacat, it is a very powerful and useful tool. That being said, I'm a little bit stuck on exactly how the offsets should be used when reading out of a topic.

I'd like to pipe a topic of json messages out of one cluster, and into another. We have a 7 day retention policy on this topic, but I really only want to grab the last 3 days and then exit.

I've tried a ton of different permutations and for some reason I can't quite figure out what I'm doing wrong:

I tried this incantation:
`kafkacat -C -e -b <broker> -t <source> -o s@<unix timestamp millis>`

I tried this incantation:
used `kafkacat -Q` to get the offsets and then feeding them as such:
`kafkacat -C -e -b <broker> -t <source> -p  <partition> -o <offset>`

I've also tried `-G "kafkacat-$(uuidgen)" <topic> -X auto.offset.reset earliest`.

Generally, the feel I'm getting is that there is a stored offset behavior, even when using the basic consumer (no -G setup), but my understanding was that unless you use a `-G`, kafkacat is not going to start with a stored offset.

**Can you help me understand what I'm doing wrong with setting the offsets so that I can grab the last X days of a topic and exit?**

**Comment by edenhill** [comment]
Add '-d consumer' to see debugging messages that show the start offset

**Comment by atheken** [comment]
Thanks at @edenhill - I was using an older version (1.3.x) that didn't support the timestamp offsets, which appeared to do _something_ but perhaps should have exploded since the format wasn't supported.
