### ISSUE TITLE
ERROR: Failed to acquire metadata: Local: Broker transport failure

### ISSUE THREAD

**Issue by AnamikaN** [edenhill/kafkacat#228]
when i am running below command , it is throwing error-
kafkacat -b xx.xxx.xxx.xxx:9092 -L -d broker

%7|1581532585.523|BROKER|rdkafka#producer-1| [thrd:app]: xx.xxx.xxx.xxx:9092/bootstrap: Added new broker with NodeId -1
%7|1581532585.523|BRKMAIN|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Enter main broker thread
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:app]: xx.xxx.xxx.xxx:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1581532585.523|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1581532585.523|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.3.0 (0x10300ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, CC CXX PKGCONFIG OSXLD LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM LZ4_EXT SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x2)
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Received CONNECT op
%7|1581532585.523|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1581532585.523|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1581532585.523|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connecting to ipv4#xx.xxx.xxx.xxx:9092 (plaintext) with socket 7
%7|1581532586.053|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connected to ipv4#xx.xxx.xxx.xxx:9092
%7|1581532586.053|CONNECTED|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connected (#1)
%7|1581532586.053|FEATURE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1581532586.053|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1581532586.053|CONNECT|rdkafka#producer-1| [thrd:app]: Cluster connection already in progress: application metadata request
%7|1581532586.053|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1581532586.524|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1581532586.570|FEATURE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Updated enabled protocol features to MsgVer1,ApiVersion,BrokerBalancedConsumer,ThrottleTime,Sasl,SaslHandshake,BrokerGroupCoordinator,LZ4,OffsetTime,MsgVer2,IdempotentProducer,ZSTD,UnitTest
%7|1581532586.570|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1581532586.934|BROKERFAIL|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1581532586.935|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state UP -> DOWN
%7|1581532586.935|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state DOWN -> INIT
%7|1581532586.935|REQERR|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: MetadataRequest failed: Local: Broker transport failure: actions Retry
%7|1581532586.935|REQERR|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: MetadataRequest failed: Local: Broker transport failure: actions Retry
%7|1581532587.527|CONNECT|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: Selected for cluster connection: no cluster connection (broker has 1 connection attempt(s))
%7|1581532587.527|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Received CONNECT op
%7|1581532587.527|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1581532587.527|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1581532587.527|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1581532587.527|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connecting to ipv4#xx.xxx.xxx.xxx:9092 (plaintext) with socket 7
%7|1581532587.527|RETRY|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Moved 2 retry buffer(s) to output queue
%7|1581532588.528|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1581532588.885|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connected to ipv4#xx.xxx.xxx.xxx:9092
%7|1581532588.885|CONNECTED|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connected (#2)
%7|1581532588.885|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1581532588.907|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1581532589.118|BROKERFAIL|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1581532589.118|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state UP -> DOWN
%7|1581532589.118|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state DOWN -> INIT
%7|1581532589.118|REQERR|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: MetadataRequest failed: Local: Broker transport failure: actions Retry
%7|1581532589.118|REQERR|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: MetadataRequest failed: Local: Broker transport failure: actions Retry
%7|1581532589.530|CONNECT|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: Selected for cluster connection: no cluster connection (broker has 2 connection attempt(s))
%7|1581532589.530|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Received CONNECT op
%7|1581532589.530|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1581532589.530|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1581532589.530|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1581532589.530|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connecting to ipv4#xx.xxx.xxx.xxx:9092 (plaintext) with socket 7
%7|1581532589.530|RETRY|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Moved 2 retry buffer(s) to output queue
%7|1581532589.623|CONNECT|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connected to ipv4#xx.xxx.xxx.xxx:9092
%7|1581532589.623|CONNECTED|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Connected (#3)
%7|1581532589.623|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1581532589.727|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state APIVERSION_QUERY -> UP
%7|1581532589.905|BROKERFAIL|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection reset by peer)
%7|1581532589.905|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state UP -> DOWN
%7|1581532589.905|STATE|rdkafka#producer-1| [thrd:xx.xxx.xxx.xxx:9092/bootstrap]: xx.xxx.xxx.xxx:9092/bootstrap: Broker changed state DOWN -> INIT
%7|1581532589.905|REQERR|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: MetadataRequest failed: Local: Broker transport failure: actions Retry
%7|1581532589.905|REQERR|rdkafka#producer-1| [thrd:main]: xx.xxx.xxx.xxx:9092/bootstrap: MetadataRequest failed: Local: Broker transport failure: actions Retry
% ERROR: Failed to acquire metadata: Local: Timed out

I can locally connect to server, i try ping and telnet

PING xx.xxx.xxx.xxx (xx.xxx.xxx.xxx): 56 data bytes
64 bytes from xx.xxx.xxx.xxx: icmp_seq=0 ttl=57 time=20.345 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=1 ttl=57 time=15.344 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=2 ttl=57 time=66.611 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=3 ttl=57 time=84.912 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=4 ttl=57 time=84.246 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=5 ttl=57 time=49.447 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=6 ttl=57 time=46.526 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=7 ttl=57 time=59.588 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=8 ttl=57 time=90.631 ms
64 bytes from xx.xxx.xxx.xxx: icmp_seq=9 ttl=57 time=101.537 ms
^C
--- xx.xxx.xxx.xxx ping statistics ---
10 packets transmitted, 10 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 15.344/61.919/101.537/27.819 ms

telnet xx.xxx.xxx.xxx 9092
Trying xx.xxx.xxx.xxx...
Connected to xx.xxx.xxx.xxx.
Escape character is '^]'.
^CConnection closed by foreign host.
w7lwildt45:~ user$ telnet xx.xxx.xxx.xxx 9093
Trying xx.xxx.xxx.xxx...
Connected to xx.xxx.xxx.xxx.

**Comment by edenhill** [comment]
This is typically caused by connecting to a SASL listener but not configuring the client for SASL authentication.
E.g, `-X security.protocol=SASL_PLAINTEXT -X sasl.mechanism=PLAIN -X sasl.username=.. -X sasl.password=..`.
But you'll need to check with the Kafka operator for the correct config.

**Comment by AnamikaN** [comment]
I am actually trying to run confluent kafka python client (https://github.com/confluentinc/confluent-kafka-python). Does it need to have sasl username/password to communicate to brokers?

**Comment by AnamikaN** [comment]
Perfect. It worked !! Than you so much edenhill !!
