### ISSUE TITLE
Does not support setting offset in KafkaClient mode

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [edenhill/kafkacat#231]
Reading from an existing and populated topic in `-G` (`KafkaClient`) mode does not allow setting the offset:

```sh
kafkacat -C -b localhost:9092 -o beginning -G cat-$RANDOM test
```

Just reads from the end (which contains nothing). For comparison, the official client 

```sh
kafka-console-consumer.sh --bootstrap-server localhost:9092 --from-beginning --topic test --group jav-$RANDOM
```

does enumerate through all the messages in the topic. I originally discovered this when trying to consume using `librdkafka` and wondered for an example on how to set the offset in the `KafkaClient` mode. But it turns out, KafkaCat does not apply any offsets in this mode and for some reason (even despite `auto.offset.reset=earliest`) it seems to default to `latest`.

**Comment by edenhill** [comment]
Fixed on maste
