### ISSUE TITLE
ERROR: Property "partitioner" must be set through dedicated .._set_..() function

### ISSUE THREAD

**Issue by winaterion** [edenhill/kafkacat#232]
Hi,
I'm using kafkacat 1.2.0-2 on linux
I'm trying to run kafkacat on linux which uses round-robin to publish events to partitions,
By Executing the following command:
`kafkacat -P -t "mytopic" -b "localhost:9092" -X topic.partitioner=murmur2_random
`
I get 

> ERROR: Property "partitioner" must be set through dedicated .._set_..() function

is this property not supported? or am I missing something?

**Comment by edenhill** [comment]
What is your librdkafka version? (`kafkacat -V`)

**Comment by winaterion** [comment]
I run the command, but it is also not supported, but still I get the version:
kafkacat: invalid option -- 'V'
Error: unknown argument

Usage: kafkacat <options> [file1 file2 ..]
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2015, Magnus Edenhill
Version KAFKACAT_VERSION (JSON) (librdkafka 0.8.6)

**Comment by edenhill** [comment]
Your librdkafka version is extremely old.

How to upgrade librdkafka depends on your OS and distro, follow the instructions here:
https://github.com/edenhill/librdkafka/#installation

**Comment by edenhill** [comment]
Or use the kafkacat docker image:
`docker run edenhill/kafkacat -V`

**Comment by winaterion** [comment]
in order to use newer version I upgraded ubuntu from 16 to Ubuntu 18.04.4 LTS (bionic)
then execute:
`apt-cache madison kafkacat`

which gives: 
```
  kafkacat |    1.3.1-1 | http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
  kafkacat |    1.3.1-1 | http://azure.archive.ubuntu.com/ubuntu bionic/universe Sources
```
so I run: 
`sudo apt-get install kafkacat=1.3.1-1`
and then:
`kafkacat -V
`
the output:
```
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2015, Magnus Edenhill
Version 1.3.1 (JSON) (librdkafka 0.11.3 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins)
```
This means kafkacat still using some old librdkafka 0.11.3, does this make sense?

**Comment by edenhill** [comment]
The package is called librdkafka1

**Comment by winaterion** [comment]
indeed, the version of librdkafka1 is 0.11.3-1build1
seems like for ubuntu 18 LTS the stable release is 0.11.3-1build1.. 
My only solution is to build it manually :/ sounds scary for production

**Comment by edenhill** [comment]
Did you add the Confluent APT repositories as instructed in the librdkafka README?
It contains the latest librdkafka version.

**Comment by winaterion** [comment]
OmG!! thanks man.... I missed the "here" link in the doc :/ now i have kafkacat_1.3.1-1amd64.deb_ and _librdkafka 1.3.0_
