### ISSUE TITLE
Support for amd64 architechture

### ISSUE THREAD

**Issue by emelyanovVlad** [edenhill/kafkacat#235]
Hello, I see you published latest 1.5.0 version last year but it doesn't exists for amd64 structure. – https://launchpad.net/ubuntu/bionic/amd64/kafkacat
Is it possible to build this version for amd64?
The latest version right now is 1.3.1

Thank you in advance

**Comment by edenhill** [comment]
I do not provide debian/ubuntu/rpm packages, you will need to file an issue with the Debian or Ubuntu projects.

**Comment by edenhill** [comment]
Or use the `edenhill/kafkacat` docker image.

**Comment by emelyanovVlad** [comment]
thank you
