### ISSUE TITLE
Kafkacat command to update the consumer groupid's offset

### ISSUE THREAD

**Issue by hello-question** [edenhill/kafkacat#237]
Hi folks, does anyone knows what is the command in kafkacat to update the consumer groupid's offset? I have produced a wrong message with error (e.g. in partition 0, offset 5) and my consumer is now stucked in the offset 5. How do I skip the message (e.g. skip the offset 5 and continue from 6)?

**Comment by edenhill** [comment]
We'll add an option to manually commit offsets.

**Comment by hello-question** [comment]
How do you add an option to manually commit offsets? I have tried this command `Kafkacat -b <broker> -t <topic> -C -p 0 -o 6` but it doesn't consume from offset 6.

**Comment by andrewkcarter** [comment]
@edenhill is this still on your todo list? Would love to be able to reset consumer group offsets using this tool.

**Comment by ChrisBerna** [comment]
@edenhill is this option already available?

**Comment by mado-vmob** [comment]
@edenhill would be great if we had this option

Also I would like to know what is the last offset. Currently there is a command which shows me the current offset. But not the end offset.

How would I commit the last offset to the end?

So Kafkacat disables autocommit, and even if I set it via the configuration file, it gets deactivated:
%7|1709035502.246|CONF|rdkafka#consumer-1| [thrd:app]:   auto.commit.enable = false
