### ISSUE TITLE
Error building on RHEL7 using bootstrap.sh

### ISSUE THREAD

**Issue by ChhatralaNirmal** [edenhill/kafkacat#240]
Hello - I am getting below error while building this project on RHEL7 using ./bootstrap.sh 
It seems ./configure doesn't have --install-deps option. 
Please advise. 

[DEV root@dfw-vd-sdp03 kafkacat]# ./bootstrap.sh
Directory librdkafka already exists, not downloading https://github.com/edenhill/librdkafka/archive/v1.4.2.tar.gz
Building librdkafka with commands:
([ -f config.h ] || ./configure --prefix=/opt/kafkacat/tmp-bootstrap/usr --install-deps --source-deps-only --disable-lz4-ext) && make -j && make install
./bootstrap.sh: line 67: ./configure: No such file or directory
Build of librdkafka FAILED!
[DEV root@dfw-vd-sdp03 kafkacat]#

**Comment by edenhill** [comment]
Try deleting tmp-bootstrap/librdkafka and try again
