### ISSUE TITLE
Kafkacat produces blank output

### ISSUE THREAD

**Issue by DwijadasDey** [edenhill/kafkacat#243]
Hi
I am running kafkacat in ubuntu 20.04 but it is unable to consume any messages from the broker. There are no errors dumped in the terminal as well.

![Screenshot_22](https://user-images.githubusercontent.com/12824049/83004296-1be22780-a02d-11ea-97bd-439efcca21f8.png)

**Comment by edenhill** [comment]
Add `-o beginning` to start reading from the start of the topic/partitions.

**Comment by DwijadasDey** [comment]
Hi
Adding `-o beginning` does not make any differences.
Regards

![Screenshot_23](https://user-images.githubusercontent.com/12824049/83015251-c5c9b000-a03d-11ea-8fa6-62fae940a273.png)

**Comment by edenhill** [comment]
Add `-d broker,topic,fetch` to see what is going on under the hood.

**Comment by DwijadasDey** [comment]
Hi
The output is attached in the file
[out.txt](https://github.com/edenhill/kafkacat/files/4688638/out.txt)

**Comment by edenhill** [comment]
The log is incomplete, can you reproduce with `-d all` instead and provide the full log?

**Comment by DwijadasDey** [comment]
[out.txt](https://github.com/edenhill/kafkacat/files/4688745/out.txt)

**Comment by edenhill** [comment]
The log is still incomplete, it starts with the consumer shutting down.
Please capture all output from start to finish:
`kafkacat ......... >log.txt 2>&1`

**Comment by DwijadasDey** [comment]
[out.txt](https://github.com/edenhill/kafkacat/files/4688848/out.txt)

**Comment by edenhill** [comment]
` Topic connect-offsets partition 18 Leader -1`

Your partitions don't have a leader broker assigned, check your kafka broker logs.
