### ISSUE TITLE
Kafkacat custom format

### ISSUE THREAD

**Issue by DwijadasDey** [edenhill/kafkacat#246]
Hi
I am running the following `kafkacat` command along with custom formatting. However the  formatting part of the output section does not show any relevant information. I can confirm the topic contains at-least one record.

![Screenshot_24](https://user-images.githubusercontent.com/12824049/83240159-9b4f3280-a1b6-11ea-97b8-ef9a90a30d6d.png)

Shall i have to use any more options ?
Regards

**Comment by edenhill** [comment]
Add `-o beginning` to start reading from the start of the partition rather than only new messages.

**Comment by DwijadasDey** [comment]
Yes, I have already included the option `-o beginning`  to read from beginning

```
#  kafkacat -b sandbox-kfk-bro1:9092 -t connect-offsets-worker -C -f '\nKey (%K bytes): %k              
  Value (%S bytes): %s
  Timestamp: %T
  Partition: %p
  Offset: %o\n'  -o beginning
```
Regards

**Comment by edenhill** [comment]
Sorry, missed that.
Make sure all partitions have leaders by `kafkacat -b $BROKERS -L -t connect-offsets-worker`, each partition should have a valid leader.
Next step is to enable debugging for the consumer by  `-d broker,topic,fetch` and see if you can detect any errors there.

**Comment by DwijadasDey** [comment]
Yes i can see `Broker: Leader not available` messages for most of the partition.

However, i have an another query:

I have three brokers - one running in SSL and PLAINTEXT mode and rest of the two in SSL mode only. I am using the broker along with the `kafkacat` command which is running in PLAINTEXT mode.  

Please confirm, This is not the reason for `Broker: Leader not available` in the kafkacat output.

Also can you point any documentation for running `kafkacat` in SSL mode ?

Thanks and regards

**Comment by edenhill** [comment]
> Yes i can see Broker: Leader not available messages for most of the partition.

Then that's the issue. Check broker logs for details.

> I have three brokers - one running in SSL and PLAINTEXT mode and rest of the two in SSL mode only.

Since a client is connected to either connect with SSL or PLAINTEXT you can't have mixed configuration on your brokers, they all need to have at least one listener that corresponds to the client config.
This most likely affects the inter-broker communication too.

> Also can you point any documentation for running kafkacat in SSL mode ?

`kafkacat -X security.protocol=ssl ..`
