### ISSUE TITLE
Kafkacat with SSL in local cluster

### ISSUE THREAD

**Issue by DwijadasDey** [edenhill/kafkacat#248]
Hi
I am having issue with kafkacat in SSL mode. I have tried with following kafkacat command.

`kafkacat -b broker2:9093 -X security.protocol=SSL -X ssl.key.location=key.pem -X ssl.key.password=password -X ssl.certificate.location=certificate.pem -X ssl.ca.location=CARoot.pem -X ssl.endpoint.identification.algorithm=none   -X enable.ssl.certificate.verification=false  -t connect-offsets -C -f '\nKey (%K bytes): %k Value (%S bytes): %s Timestamp: %T Partition: %p Offset: %o\n' -d broker,topic,fetch`

However, the kafkacat is producing `ERROR: Failed to query metadata for topic connect-offsets: Local: Broker transport failure` 

In the kafka broker, the log entry is:

`Failed authentication with /172.16.10.220 (SSL handshake failed) (org.apache.kafka.common.network.Selector)`

Kafka brokers are configured with `ssl.client.auth=none`

For kafkacat, I am generating keys and certificates for kafkacat from the JKS keys those i had generated earlier to run kafka producer and consumer and are working fine. The client configuration for kafka producer/consumer is:

```
security.protocol=SSL
ssl.truststore.location=/u01/cnfkp/confluent-kfk/etc/ssl/client_cert/kafka.client.truststore.jks
ssl.truststore.password=password
ssl.keystore.location=/u01/cnfkp/confluent-kfk/etc/ssl/client_cert/kafka.client.keystore.jks
ssl.keystore.password=password
ssl.key.password=password
ssl.endpoint.identification.algorithm=
```

So when i am using  `kafka.client.keystore.jks` and `kafka.client.truststore.jks`  along with kafka producer and consumer, it can connect to broker using SSL.

Generated keys and certificates for kafkacat from keystore file like following:

```
Value of ssl.certificate.location(certificate.pem)
# keytool -exportcert -alias kafkaclient -keystore kafka.client.keystore.jks -rfc -file certificate.pem

Value of ssl.key.location(key.pem)
# keytool -v -importkeystore -srckeystore kafka.client.keystore.jks -srcalias kafkaclient -destkeystore cert_and_key.p12 -deststoretype PKCS12
# openssl pkcs12 -in cert_and_key.p12 -nocerts -nodes -out key.pem

Value of ssl.ca.location(CARoot.pem)
# keytool -exportcert -alias CARoot -keystore kafka.client.keystore.jks -rfc -file CARoot.pem
```

What i guess the issue may be with `ssl.endpoint.identification.algorithm` which is set to none although i have tried with `https` as well.

What is wrong with the above steps ?

**Comment by DwijadasDey** [comment]
Hi
I think in the process of generating keys for kafkacat.  i have to use the option `-keyalg RSA` along with `keytool` command. I tried to produce a simple message using kafkacat but got the following error:

```
$ echo "Hello" | kafkacat -P -b sandbox-kfk-bro1.infodetics.com:9093 -t test -X security.protocol=SSL -X ssl.ca.location=CARoot.pem 
%3|1591183763.131|FAIL|rdkafka#producer-1| [thrd:ssl://sandbox-kfk-bro1.infodetics.com:9093/bootstrap]: ssl://sandbox-kfk-bro1.infodetics.com:9093/bootstrap: SSL handshake failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (after 2ms in state CONNECT)
% ERROR: Local: SSL error: ssl://sandbox-kfk-bro1.infodetics.com:9093/bootstrap: SSL handshake failed: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (after 2ms in state CONNECT)
% ERROR: Local: All broker connections are down: 1/1 brokers are down : terminating
```
On digging a little bit related to this error, i found this [issue](https://github.com/edenhill/librdkafka/issues/1765).

Also, connecting kafka broker using `openssl s_client` results in following . From the output, it looks i have the correct certificates and configurations in place.

The following `openssl s_client` command also includes `ssl3_get_record:wrong version` error.
```
$ openssl s_client -CAfile CARoot.pem -host sandbox-kfk-bro2.infodetics.com -port 9093 -showcerts
CONNECTED(00000003)
140456563660096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../ssl/record/ssl3_record.c:331:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 323 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

@edenhill , can you confirm the issue is with generating keys for brokers and kafkacat without RSA ?

Regards

**Comment by edenhill** [comment]
I unfortunately don't know enough about SSL to be able to verify this, but it sounds plausible.

**Comment by DwijadasDey** [comment]
Hi
@edenhill 
The procedure described in the above section works fine after i compiled and re-installed kafkacat from scratch again.
Regards

**Comment by msravan** [comment]
FYI, In case anyone facing this issue on Mac OS, here are the steps to make it work. 

- By default, Mac OS' default openssl is used, we need to use the librakafka openssl with 'brew install openssl'
- Link to the newly installed openssl version, it's version 3 in the following example. Run the following commands with your version of openssl installed.
>  ln -s /usr/local/opt/openssl/lib/libcrypto.3.dylib /usr/local/lib/
> ln -s /usr/local/opt/openssl/lib/libssl.3.dylib /usr/local/lib/
> ln -s /usr/local/Cellar/openssl\@3/3.0.0/bin/openssl  /usr/local/bin/openssl
> export PATH="$PATH:/usr/local/Cellar/openssl\@3/3.0.0/bin/openssl"

- update cert.pem  in /etc/ssl/certs/ with your ca-chain content

**Comment by pederpansen** [comment]
Hi @msravan, could you elaborate on how to do this:

>     * update cert.pem  in /etc/ssl/certs/ with your ca-chain content

What exactly should be the contents of the `cert.pem` file and where do I get it from?

**Comment by vsethi13** [comment]
I was able to get it working with this command:
```
kcat -b broker:9093 -t my-topic -X security.protocol=SSL -X ssl.certificate.location=/path/to/cert.pem -X ssl.key.location=/path/to/cert_key.pem -X ssl.ca.location=/path/to/ca.pem -X enable.ssl.certificate.verification=false
```

Note that my cert_key.pem was decrypted already.
Kafkcat version:
```                                                                                                                                                                                               
kcat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kcat
Copyright (c) 2014-2021, Magnus Edenhill
Version 1.7.0 (JSON, Avro, Transactions, IncrementalAssign, librdkafka 2.2.0 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer,http,oidc)
```

**Comment by dennisharrison** [comment]
> I was able to get it working with this command:
> 
> ```
> kcat -b broker:9093 -t my-topic -X security.protocol=SSL -X ssl.certificate.location=/path/to/cert.pem -X ssl.key.location=/path/to/cert_key.pem -X ssl.ca.location=/path/to/ca.pem -X enable.ssl.certificate.verification=false
> ```
> 
> Note that my cert_key.pem was decrypted already. Kafkcat version:
> 
> ```
> kcat - Apache Kafka producer and consumer tool
> https://github.com/edenhill/kcat
> Copyright (c) 2014-2021, Magnus Edenhill
> Version 1.7.0 (JSON, Avro, Transactions, IncrementalAssign, librdkafka 2.2.0 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer,http,oidc)
> ```

Thank you from 2024 - this was helpful
