### ISSUE TITLE
Failed to acquire metadata: Local: Broker transport failure

### ISSUE THREAD

**Issue by danishkamili** [edenhill/kafkacat#256]
kafkacat -L -b loyalty-prod-kafkabroker01.integration.abc.io:443 -d broker,protocol,cgrp
%7|1595257485.467|BROKER|rdkafka#producer-1| [thrd:app]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Added new broker with NodeId -1
%7|1595257485.467|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1595257485.468|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1595257485.468|BRKMAIN|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Enter main broker thread
%7|1595257485.470|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: broker in state INIT connecting
%7|1595257485.486|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connecting to ipv4#10.136.212.46:443 (plaintext) with socket 7
%7|1595257485.490|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state INIT -> CONNECT
%7|1595257485.528|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected to ipv4#10.136.212.46:443
%7|1595257485.535|CONNECTED|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected (#1)
%7|1595257485.546|FEATURE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1595257485.551|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1595257485.566|SEND|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 1)
%7|1595257485.755|BROKERFAIL|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: failed: err: Local: Broker transport failure: (errno: Operation now in progress)
%7|1595257485.765|FEATURE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Updated enabled protocol features -ApiVersion to
%7|1595257485.766|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state APIVERSION_QUERY -> DOWN
%7|1595257485.769|REQERR|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: explicit actions 0x0
%7|1595257485.778|BROKERFAIL|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: failed: err: Local: Not implemented: (errno: Operation now in progress)
%7|1595257485.787|FAIL|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: probably due to old broker version
%7|1595257485.788|RECONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Delaying next reconnect by 375ms
%7|1595257486.174|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: broker in state DOWN connecting
%7|1595257486.177|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connecting to ipv4#10.136.214.106:443 (plaintext) with socket 7
%7|1595257486.185|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state DOWN -> CONNECT
% ERROR: Failed to acquire metadata: Local: Broker transport failure

**Comment by danishkamili** [comment]
kafkacat -L -b loyalty-prod-kafkabroker01.integration.abc.io:443 -d broker,protocol,cgrp
%7|1595257672.413|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1595257672.413|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1595257672.413|BROKER|rdkafka#producer-1| [thrd:app]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Added new broker with NodeId -1
%7|1595257672.414|BRKMAIN|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Enter main broker thread
%7|1595257672.414|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: broker in state INIT connecting
%7|1595257672.498|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connecting to ipv4#10.136.213.145:443 (plaintext) with socket 7
%7|1595257672.500|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state INIT -> CONNECT
%7|1595257672.622|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected to ipv4#10.136.213.145:443
%7|1595257672.624|CONNECTED|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected (#1)
%7|1595257672.624|FEATURE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Updated enabled protocol features +ApiVersion to ApiVersion
%7|1595257672.625|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
%7|1595257672.626|SEND|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Sent ApiVersionRequest (v0, 25 bytes @ 0, CorrId 1)
%7|1595257672.762|BROKERFAIL|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: failed: err: Local: Broker transport failure: (errno: Operation now in progress)
%7|1595257672.763|FEATURE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Updated enabled protocol features -ApiVersion to
%7|1595257672.764|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state APIVERSION_QUERY -> DOWN
%7|1595257672.764|REQERR|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: explicit actions 0x0
%7|1595257672.764|BROKERFAIL|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: failed: err: Local: Not implemented: (errno: Operation now in progress)
%7|1595257672.765|FAIL|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: ApiVersionRequest failed: Local: Broker transport failure: probably due to old broker version
%7|1595257672.765|RECONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Delaying next reconnect by 56ms
%7|1595257672.821|RECONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Delaying next reconnect by 49ms
%7|1595257672.870|RECONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Delaying next reconnect by 187ms
%7|1595257673.059|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: broker in state DOWN connecting
%7|1595257673.064|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connecting to ipv4#10.136.212.46:443 (plaintext) with socket 7
%7|1595257673.073|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state DOWN -> CONNECT
%7|1595257673.196|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected to ipv4#10.136.212.46:443
%7|1595257673.200|CONNECTED|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected (#2)
%7|1595257673.210|APIVERSION|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Using (configuration fallback) 0.9.0 protocol features
%7|1595257673.218|FEATURE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Updated enabled protocol features to BrokerBalancedConsumer,ThrottleTime,Sasl,BrokerGroupCoordinator,LZ4
%7|1595257673.225|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state CONNECT -> UP
%7|1595257673.233|SEND|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Sent MetadataRequest (v0, 25 bytes @ 0, CorrId 2)
%7|1595257673.251|SEND|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Sent MetadataRequest (v0, 25 bytes @ 0, CorrId 3)
%7|1595257673.289|BROKERFAIL|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: failed: err: Local: Broker transport failure: (errno: Operation now in progress)
%7|1595257673.296|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state UP -> DOWN
%7|1595257673.305|RETRY|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Retrying MetadataRequest (v0, 25 bytes, retry 1/2)
%7|1595257673.308|RETRY|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Retrying MetadataRequest (v0, 25 bytes, retry 1/2)
%7|1595257673.416|RECONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Delaying next reconnect by 39ms
%7|1595257673.460|RECONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Delaying next reconnect by 305ms
%7|1595257673.769|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: broker in state DOWN connecting
%7|1595257673.794|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connecting to ipv4#10.136.213.145:443 (plaintext) with socket 7
%7|1595257673.797|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state DOWN -> CONNECT
%7|1595257673.833|CONNECT|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected to ipv4#10.136.213.145:443
%7|1595257673.835|CONNECTED|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Connected (#3)
%7|1595257673.844|APIVERSION|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Using (configuration fallback) 0.9.0 protocol features
%7|1595257673.847|STATE|rdkafka#producer-1| [thrd:loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap]: loyalty-prod-kafkabroker01.integration.abc.io:443/bootstrap: Broker changed state CONNECT -> UP
% ERROR: Failed to acquire metadata: Local: Timed out

**Comment by danishkamili** [comment]
Kafka Cluster: Strimzi Kafka
Access to Kafka through Ingress with TLS/SSL Passthrough enable on ingress-nginx

**Comment by edenhill** [comment]
It looks like you're trying to connect to an SSL broker listener with a plaintext connection, which will not work.
Use `-X security.protocol=SSL` to enable SSL.

**Comment by danishkamili** [comment]
@edenhill  tried, still same:

kafkacat -L -b internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094 -d broker,protocol
%7|1595336153.226|BROKER|rdkafka#producer-1| [thrd:app]: internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Added new broker with NodeId -1
%7|1595336153.226|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1595336153.227|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1595336153.227|BRKMAIN|rdkafka#producer-1| [thrd:internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.]: internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Enter main broker thread
%7|1595336153.228|CONNECT|rdkafka#producer-1| [thrd:internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.]: internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: broker in state INIT connecting
%7|1595336153.242|CONNECT|rdkafka#producer-1| [thrd:internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.]: internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Connecting to ipv4#10.136.213.205:9094 (plaintext) with socket 7
%7|1595336153.243|STATE|rdkafka#producer-1| [thrd:internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.]: internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Broker changed state INIT -> CONNECT
% ERROR: Failed to acquire metadata: Local: Broker transport failure


abcd4344@C-5CG92044HQ:~/kafka/strimzi-kafka$ kafkacat -X security.protocol=ssl -L -b internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094 -d broker,protocol
%7|1595336182.129|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1595336182.129|BROKER|rdkafka#producer-1| [thrd:app]: ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Added new broker with NodeId -1
%7|1595336182.129|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1595336182.130|BRKMAIN|rdkafka#producer-1| [thrd:ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-e]: ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Enter main broker thread
%7|1595336182.131|CONNECT|rdkafka#producer-1| [thrd:ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-e]: ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: broker in state INIT connecting
%7|1595336182.148|CONNECT|rdkafka#producer-1| [thrd:ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-e]: ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Connecting to ipv4#10.136.214.195:9094 (ssl) with socket 9
%7|1595336182.150|STATE|rdkafka#producer-1| [thrd:ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-e]: ssl://internal-aaa1e74jhjdhdiwhkhuuif0f88jnn77-1039168229.us-east-1.elb.amazonaws.com:9094/bootstrap: Broker changed state INIT -> CONNECT
% ERROR: Failed to acquire metadata: Local: Broker transport failure

**Comment by danishkamili** [comment]
I deployed it using helm and strimzi 0.18.0

helm:  values.yaml


name: strimzi-kafka

kafka:
  replicas: 3
  storage:
    size: 400Gi
    class: gp2
  defaultReplicationFactor: 3
  minInSyncReplicas: 2
  logCleanupPolicy: compact
  nodegroups: kafka

zookeeper:
  replicas: 3
  storage:
    size: 400Gi
    class: gp2
  nodegroups: kafka

entityOperator:
  nodegroups: kafka

  topicOperator:
    watchedNamespace: kafka


2) templates/kafka.yaml

apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.name }}
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      plain: {}
      tls: {}
      external:
        type: loadbalancer
        authentication:
         type: tls
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class }}
      deleteClaim: false
    metrics: {}
    template:
      externalBootstrapService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: nodegroups
                      operator: In
                      values:
                        - {{ .Values.kafka.nodegroups }}
        tolerations:
          - key: dedicated
            value: {{ .Values.kafka.nodegroups }}
            effect: NoSchedule
      kafkaContainer:
        env:
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: {{ .Values.kafka.defaultReplicationFactor | quote }}
          - name: KAFKA_MIN_INSYNC_REPLICAS
            value: {{ .Values.kafka.minInSyncReplicas | quote }}
          - name: KAFKA_LOG_CLEANUP_POLICY
            value: {{ .Values.kafka.logCleanupPolicy }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class }}
      deleteClaim: false
    metrics: {}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: nodegroups
                      operator: In
                      values:
                        - {{ .Values.zookeeper.nodegroups }}
        tolerations:
          - key: dedicated
            value: {{ .Values.zookeeper.nodegroups }}
            effect: NoSchedule
  entityOperator:
    topicOperator:
      watchedNamespace: {{ .Values.entityOperator.topicOperator.watchedNamespace }}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: nodegroups
                      operator: In
                      values:
                        - {{ .Values.entityOperator.nodegroups }}
        tolerations:
          - key: dedicated
            value: {{ .Values.entityOperator.nodegroups }}
            effect: NoSchedule

**Comment by danishkamili** [comment]
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.name }}
spec:
  kafka:
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      plain: {}
      tls: {}
      external:
        type: loadbalancer
        authentication:
         type: tls
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      class: {{ .Values.kafka.storage.class }}
      deleteClaim: false
    metrics: {}
    template:
      externalBootstrapService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: nodegroups
                      operator: In
                      values:
                        - {{ .Values.kafka.nodegroups }}
        tolerations:
          - key: dedicated
            value: {{ .Values.kafka.nodegroups }}
            effect: NoSchedule
      kafkaContainer:
        env:
          - name: KAFKA_DEFAULT_REPLICATION_FACTOR
            value: {{ .Values.kafka.defaultReplicationFactor | quote }}
          - name: KAFKA_MIN_INSYNC_REPLICAS
            value: {{ .Values.kafka.minInSyncReplicas | quote }}
          - name: KAFKA_LOG_CLEANUP_POLICY
            value: {{ .Values.kafka.logCleanupPolicy }}
  zookeeper:
    replicas: {{ .Values.zookeeper.replicas }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class }}
      deleteClaim: false
    metrics: {}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: nodegroups
                      operator: In
                      values:
                        - {{ .Values.zookeeper.nodegroups }}
        tolerations:
          - key: dedicated
            value: {{ .Values.zookeeper.nodegroups }}
            effect: NoSchedule
  entityOperator:
    topicOperator:
      watchedNamespace: {{ .Values.entityOperator.topicOperator.watchedNamespace }}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: nodegroups
                      operator: In
                      values:
                        - {{ .Values.entityOperator.nodegroups }}
        tolerations:
          - key: dedicated
            value: {{ .Values.entityOperator.nodegroups }}
            effect: NoSchedule

**Comment by danishkamili** [comment]
[kafka.txt](https://github.com/edenhill/kafkacat/files/4953659/kafka.txt)

Kafka.YAML

**Comment by danishkamili** [comment]
Values.YAML
[values.txt](https://github.com/edenhill/kafkacat/files/4953665/values.txt)

**Comment by danishkamili** [comment]
deployed without helm, still same issue:
kubectly apply -f kafka.yaml 

Kafka.yaml
---
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 2.5.0 # Kafka version
    replicas: 3 # Replicas specifies the number of broker nodes.
    listeners: # Listeners configure how clients connect to the Kafka cluster
      plain: {} # 9092
      tls: {} # 9093
      external:
        type: loadbalancer
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
      delete.topic.enable: "true"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim # Persistent storage backed by AWS EBS
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {} # Operator for topic administration
    userOperator: {}

**Comment by edenhill** [comment]
If the broker is stuck in CONNECT state it means the connection attempt is still ongoing, which is typically an indication of routing/network issues, the broker address being unavailable/unreachable from the client.
This is outside the control of the client, debug your container/network environment.

**Comment by danishkamili** [comment]
Its fixed now, thanks
