### ISSUE TITLE
Apt version currently at 1.3.1 when current version is 1.6

### ISSUE THREAD

**Issue by chuck-confluent** [edenhill/kafkacat#258]
Hey Magnus,

It looks like the `-F` option was introduced sometime between 1.3 and the current version (1.6), which would be SUPER useful with testing security settings. Unfortunately, `apt-get install kafkacat` currently installs 1.3.1. I'd love to ditch the traditional command line tools and their clunky, non-uniform `--command-config` type options in favor of kafkacat, with a simple apt install. Maybe there's some kink in the pipeline from the source code to apt publishing?

Thanks for your work!

**Comment by chuck-confluent** [comment]
Oh, and not to mention I'd love to take advantage of librdkafka 1.5 features with kafkacat with a simple apt install as well!

**Comment by edenhill** [comment]
The kafkacat project does not have the ability to push new versions to the Debian packaging repositories, this is done by the Debian maintainer @vincentbernat in whatever release cadence Debian has.

**Comment by edenhill** [comment]
This is also the reason why I provide docker images with an up to date kafkacat&librdkafka with all options enabled: `edenhill/kafkacat:1.6.0`

**Comment by vincentbernat** [comment]
In Debian stable, only security fixes and important bug fixes may trigger a new release of a package. There is the ability to upload more recent versions as a backport but I don't currently have much time for that.
