### ISSUE TITLE
Use `fflush()` after `fwrite()` to allow consumer to be piped to another process

### ISSUE THREAD

**Issue by vincentbernat** [edenhill/kafkacat#26]
Hi!

Currently, if we do `kafkacat -C | someprogram`, even when the target program is handling unbuffered input, we don't get the last few received messages because the libc is buffering `fwrite()` output when it is not a terminal. Adding a `fflush(fp)` solves this issue.

**Comment by vincentbernat** [comment]
Well, there is the `-u` option just for that. I had to post the issue to find it. ;-)

**Comment by edenhill** [comment]
:)
