### ISSUE TITLE
Kafkacat ignores `::` key delimiter.

### ISSUE THREAD

**Issue by uraniumdawn** [edenhill/kafkacat#260]
My file `sample.json` with key/message example looks like `customkey::{ "foo": "bar"}`
I use it for producing: `kafkacat -b localhost:9092 -t my-topic -P -K::  -l sample.json` and expect in consumer (`kafkacat -b localhost:9092 -t my-topic -C -f 'Key: %k, Value: %s\n'`) something like this:
`Key: customkey, Value: { "foo": "bar"}`
but get the
 `Key: customkey, Value: :{ "foo": "bar"}`
The additional colon has been appeared:) Looks like kafkacat ignore second colon in `-K::` and split only by first one.
Isn't `::` allowed like a delimiter?

**Comment by edenhill** [comment]
The message delimiter is currently limited to one single byte, the extra bytes are ignored.

**Comment by rmoff** [comment]
(Duplicate of #140 )

**Comment by qiujiangkun** [comment]
This should give a warning

> The message delimiter is currently limited to one single byte, the extra bytes are ignored.
