### ISSUE TITLE
Kafkacat not exiting when -G option is used

### ISSUE THREAD

**Issue by imsathyakumar** [edenhill/kafkacat#264]
Kafkacat is exiting as expected using `-e` when Consumer group is not passed. When `-G` is passed, Kafkacat hangs in there

```bash
kafkacat -b my-bootstrap:9092 -e -G hold-cg-test hold-test
% Waiting for group rebalance
% Group hold-cg-test rebalanced (memberid rdkafka-d14489f0-d1c8-4056-9d01-295ab518667b): assigned: hold-test [0]
% Reached end of topic hold-test [0] at offset 4

^C% Group hold-cg-test rebalanced (memberid rdkafka-d14489f0-d1c8-4056-9d01-295ab518667b): revoked: hold-test [0]
```

**Comment by johnrkriter** [comment]
Whats odd about this is it seems that the high-level consumer knows its reached the end of the topic. For example, if I do `-o -100` to read the 100 most recent events it will "reached end of partition but the thread doesnt end.
