### ISSUE TITLE
Add to yum

### ISSUE THREAD

**Issue by mattburman** [edenhill/kafkacat#276]
Is there any chance of adding Kafkacat to yum?

I've tried building from source, but I've not been able to get the new Avro support working. My familiarity with C/C++ is minimal.
I can run it in Docker, but it would be easier for my team with a binary so we don't need to mount volumes for the config and certificates.

I have followed the Blog post by @rmoff to build from source but most of my struggling was during this bit
> If you get errors here, it’s off to Google you go to try and figure them out

**Comment by edenhill** [comment]
I do not have the time to provide deb or rpms, but people are free to file issues with their favourite Linux distros and ask them to add the package, or maintain these packages themselves.
