### ISSUE TITLE
Print partition id of the message

### ISSUE THREAD

**Issue by ibalashov** [edenhill/kafkacat#28]
Would be great to have the ability to see the partition id of the messages, similar to offsets printed with `-O` flag. 

Better yet, since offsets belong to partitions it would make sense to prepend them with partition id, e.g. `0:12345`

**Comment by edenhill** [comment]
Good idea!

I think it might be time to make the output truly customizable by providing a format string, e.g.:
`kafkacat ... -F "%t: %o:%p: %k: %s"`

Where:
 * %t - topic
 * %o - offset
 * %p - partition
 * %k - key
 * %s - message payload

Additionally kafkacat should be able to output a JSON envelope with the same information, e.g.:
`kafkacat ... -J topic,offset,partition,key,payload`

**Comment by ibalashov** [comment]
Yeah, custom output format would be much better. Would also allow to eliminate arguments `-O` and `-K` with its special `CTRL-V TAB` console delimiter magic.
JSON option is also sounds great.

**Comment by ibalashov** [comment]
Would be great to include keys in default format output. To be honest, I don't quite understand the motivation NOT to include keys. In case they are not empty, chances are they are needed in the output. If they are empty, any short meta symbol won't clutter the output.

**Comment by edenhill** [comment]
You are right, but, I dont want to change the defaults (without a major version bump) since that will break scripts using kafkacat.
Also, historically the key has mostly been used on the producer side of things for partitioning, it is more recently that more wide spread use of the key on the consumer side has taken place, mainly thanks to log compaction semantics.

**Comment by edenhill** [comment]
I've now added variable output formatting that lets you define the output format
with the `-f` command line argument, e.g.:
`kafkacat -C -b 0 -t test -p 0   -f 'topic %t[%p] @ offset %o: key=%k: %s'`

This is currently in a feature branch, `json_support`, that adds support for JSON output aswell (`-J`).

Can you please try it out and see if you like it?

**Comment by ibalashov** [comment]
Hm, I seem to have lost the ability to build it since `cmake` is now required, and I get the the following error trying to install it on `Ubuntu 12.04.3 LTS`:

```
sudo apt-get install cmake
The following packages have unmet dependencies:
 cmake : Depends: cmake-data (>= 2.8.12.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Will give it another look shortly.

**Comment by edenhill** [comment]
On Ubuntu you could install `libyajl-dev` directly instead (and dont run bootstrap.sh)

**Comment by ibalashov** [comment]
Thanks for the suggestion, but I've managed to install `cmake` and `./bootstrap.sh` is back to working state.

A quick test revealed a couple of possible issues:
1) Empty output if mode is not set explicitly, even though `Auto-selecting Consumer mode` is displayed
Setting `-C` solves it

2) If format contains `%m` but message part is empty the following error is produced:
`% ERROR: Unsupported formatter: %m`

**Comment by edenhill** [comment]
**1)** is fixed

**2)** %m is not a supported formatter, %s is what you are looking for. Do you think it makes more sense to have %m instead?

**Comment by edenhill** [comment]
Maybe bootstrap should continue, with JSON disabled, if libyajl cannot be built, to avoid having bootstrap actually depend on externals (cmake). What do you think?

**Comment by ibalashov** [comment]
Re `2)`, `%m` might be a bit more intuitive, although it clashes with a notion of message itself, so `%s` is fine, apart from the typo in example:
```
Example:
  -f 'Topic %t [%p] at offset %o: key %k: %m\n'
```

> Maybe bootstrap should continue


Yes, this would be great idea. Definitely would help with nightly installs on boxes with `Ubuntu 12.04`

**Comment by edenhill** [comment]
Great, I kept %s.

libyajl is now optional in bootstrap as well.

All this was just pushed to master, please give it a spin.

**Comment by ibalashov** [comment]
You might still want to fix that typo, otherwise works great, thanks!

**Comment by edenhill** [comment]
Awesome!
