### ISSUE TITLE
delimiter flag -D not supporting empty string value any more

### ISSUE THREAD

**Issue by Stu-P** [edenhill/kafkacat#280]
Not sure if this is really an issue, perhaps a misunderstanding, but did cause me an issue so thought id mention it. I am piping the output of kafkacat into protobuf compiler to query values, using the solution here https://github.com/edenhill/kafkacat/issues/72

specifically I must provide the empty string delimiter or else the parsing fails (at least with any other delimiter I can think of, or if i provide no delimiter flag) 
... \
-D "" -e | protoc --decode_raw 

After building with the latest master branch I am now getting an error
% ERROR: Message delimiter -D must be exactly one byte (no multi-byte unicode code points)

Seems fair that I should provide a charactor if im using the flag but does seem to mean I can no longer decode protobuf messages using the above technique.

I went back and build with tag 1.5.0 and the _-D "" -e | protoc --decode_raw_ works with this code so I will just use the older version, but would be good to have a solution for this use case.

**Comment by amit-handda** [comment]
@edenhill may I know why this was marked as `completed`. is `kcat` broken for this usecase ? for >= 1.5.0 ? thanks
