### ISSUE TITLE
Error: "Cluster connection already in progress: no cluster connection"  (only inside docker container)

### ISSUE THREAD

**Issue by mradspieler** [edenhill/kafkacat#283]
Hi,

if I run
`kafkacat -L -b XXXXXX.azure.confluent.cloud:9092 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN -X sasl.username=testuser -X sasl.password=1234 -d broker`
%7|1605875820.312|TERMINATE|rdkafka#producer-1| [thrd:sasl_ssl://XXXXXX.azure.confluent.cloud:9092/boot]: sasl_ssl://XXXXXX.azure.confluent.cloud:9092/bootstrap: Handle is terminating in state DOWN: 1 refcnts (0x563ddd50b6c0), 0 toppar(s), 0 active toppar(s), 0 outbufs, 0 waitresps, 0 retrybufs: failed 0 request(s) in retry+outbuf
%7|1605875820.312|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_ssl://XXXXXX.azure.confluent.cloud:9092/boot]: sasl_ssl://XXXXXX.azure.confluent.cloud:9092/bootstrap: failed: err: Local: Broker handle destroyed: (errno: Success)

everthing is working fine, but if I run it inside docker 
`docker run edenhill/kafkacat:1.6.0 -L -v -b XXXXXX.azure.confluent.cloud:9092 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN -X sasl.username=testuser -X sasl.password=1234 -d broker`

%7|1605878591.122|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1605878591.145|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://XXXXXX.azure.confluent.cloud:9092/boot]: sasl_ssl://XXXXXX.azure.confluent.cloud:9092/bootstrap: Connected to ipv4#104.45.79.123:9092
....
%7|1605878591.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605878592.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605878593.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605878594.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605878595.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605878595.672|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
% Fatal error at metadata_list:1006:
% ERROR: Failed to acquire metadata: Local: Broker transport failure

Any hints/solutions for that problem?
- Markus

**Comment by edenhill** [comment]
Can you reproduce this with `-d security,broker,protocol` and provide the full log? Also provide the output from `kafkacat -V`

**Comment by mradspieler** [comment]
Hi Magnus,

thanks for the quick response.

`docker run edenhill/kafkacat:1.6.0 -L -v -b 123.westeurope.azure.confluent.cloud:9092 -X security.protocol=SASL_SSL -X sasl.mechanisms=PLAIN -X sasl.username=USERNAME -X sasl.password=PASSWORD -d security,broker,protocol`
%7|1605883555.657|SASL|rdkafka#producer-1| [thrd:app]: Selected provider PLAIN (builtin) for SASL mechanism PLAIN
%7|1605883555.657|OPENSSL|rdkafka#producer-1| [thrd:app]: Using OpenSSL version OpenSSL 1.1.1g  21 Apr 2020 (0x1010107f, librdkafka built with 0x1010107f)
%7|1605883555.672|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1605883555.672|BROKER|rdkafka#producer-1| [thrd:app]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Added new broker with NodeId -1
%7|1605883555.672|CONNECT|rdkafka#producer-1| [thrd:app]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Selected for cluster connection: bootstrap servers added (broker has 0 connection attempt(s))
%7|1605883555.672|BRKMAIN|rdkafka#producer-1| [thrd:sasl_ssl://123.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Enter main broker thread
%7|1605883555.672|INIT|rdkafka#producer-1| [thrd:app]: librdkafka v1.5.0 (0x10500ff) rdkafka#producer-1 initialized (builtin.features gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer, GCC GXX PKGCONFIG GNULD C11THREADS LIBDL PLUGINS ZLIB SSL SASL_CYRUS ZSTD HDRHISTOGRAM SYSLOG SNAPPY SOCKEM SASL_SCRAM SASL_OAUTHBEARER CRC32C_HW, debug 0x282)
%7|1605883555.672|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://123.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Received CONNECT op
%7|1605883555.673|STATE|rdkafka#producer-1| [thrd:sasl_ssl://123.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Broker changed state INIT -> TRY_CONNECT
%7|1605883555.672|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1605883555.673|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://123.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://pkc-43yqo.westeurope.azure.confluent.cloud:9092/bootstrap: broker in state TRY_CONNECT connecting
%7|1605883555.673|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1605883555.673|STATE|rdkafka#producer-1| [thrd:sasl_ssl://123.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Broker changed state TRY_CONNECT -> CONNECT
%7|1605883555.673|CONNECT|rdkafka#producer-1| [thrd:app]: Not selecting any broker for cluster connection: still suppressed for 49ms: application metadata request
%7|1605883555.677|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://123.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Connecting to ipv4#104.45.79.88:9092 (sasl_ssl) with socket 7
%7|1605883555.697|CONNECT|rdkafka#producer-1| [thrd:sasl_ssl://123.westeurope.azure.confluent.cloud:9092/boot]: sasl_ssl://123.westeurope.azure.confluent.cloud:9092/bootstrap: Connected to ipv4#104.45.79.123:9092
%7|1605883556.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605883557.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605883558.672|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605883559.673|CONNECT|rdkafka#producer-1| [thrd:main]: Cluster connection already in progress: no cluster connection
%7|1605883560.673|CONNECT|rdkafka#producer-1| [thrd:app]: Cluster connection already in progress: application metadata request
% Fatal error at metadata_list:1006:
% ERROR: Failed to acquire metadata: Local: Broker transport failure
%7|1605883560.673|CONNECT|rdkafka#producer-1| [thrd:main]: Not selecting any broker for cluster connection: still suppressed for 49ms: no cluster connection

kafka-2:~$ `kafkacat -V`
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2019, Magnus Edenhill
Version 1.5.0 (JSON, librdkafka 1.2.1 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,sasl_oauthbearer)

kafka-2:~$ `docker run edenhill/kafkacat:1.6.0 -V`
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2019, Magnus Edenhill
Version 1.6.0 (JSON, Avro, Transactions, librdkafka 1.5.0 builtin.features=gzip,snappy,ssl,sasl,regex,lz4,sasl_gssapi,sasl_plain,sasl_scram,plugins,zstd,sasl_oauthbearer)

Thanks for your help,
- Markus

**Comment by edenhill** [comment]
Seems like it hangs during SSL negotiation, but that exact same command line (with the broker replaced) works for me, so shouldn't be an issue with the docker image itself.

What's the host machine? Linux? OSX?

**Comment by edenhill** [comment]
Try `docker run --network=host ..` or `bridge`.

**Comment by mradspieler** [comment]
thanks! this is the solution
