### ISSUE TITLE
kafkacat tries to resolve host with port as host: Failed to resolve 'ecsc00a060af.epam.com:9092': Name does not resolve

### ISSUE THREAD

**Issue by Hubbitus** [edenhill/kafkacat#284]
```
$ podman run -it --network=host docker.io/edenhill/kafkacat:1.6.0 -b PLAINTEXT://ecsc00a060af.epam.com -L
%3|1606162721.123|FAIL|rdkafka#producer-1| [thrd:ecsc00a060af.epam.com:9092/bootstrap]: ecsc00a060af.epam.com:9092/bootstrap: Failed to resolve 'ecsc00a060af.epam.com:9092': Name does not resolve (after 34ms in state CONNECT)
%3|1606162723.093|FAIL|rdkafka#producer-1| [thrd:ecsc00a060af.epam.com:9092/bootstrap]: ecsc00a060af.epam.com:9092/bootstrap: Failed to resolve 'ecsc00a060af.epam.com:9092': Name does not resolve (after 4ms in state CONNECT, 1 identical error(s) suppressed)
% ERROR: Failed to acquire metadata: Local: Broker transport failure
```

It looks something similar to https://github.com/edenhill/kafkacat/issues/209 but I'm on Fedora Linux 33 and not on MacOS

**Comment by Hubbitus** [comment]
And I have cluster only with 5 nodes, not 256.

**Comment by edenhill** [comment]
Your docker container can't resolve the broker. Check its resolver and network settings.

**Comment by Hubbitus** [comment]
But `kafkacat` tires resolve host `ecsc00a060af.epam.com:9092` it is indeed incorrect! ecsc00a060af.epam.com what placed in parameters resolved correctly!

**Comment by edenhill** [comment]
You can ignore the :9092 port, it is not part of what is being resolved.

**Comment by Hubbitus** [comment]
Yeh, indeed it is [split DNS and systemd-resolved](https://fedoramagazine.org/systemd-resolved-introduction-to-split-dns/) in action. Sorry for the noise.
