### ISSUE TITLE
Error consuming message with empty 'message' part

### ISSUE THREAD

**Issue by ibalashov** [edenhill/kafkacat#29]
Upon consuming a message which does not have a message part (key only), kafkacat fails with error: 

`% ERROR: Write error for message of 0 bytes at offset 18): Undefined error: 0` 

On a relevant note, `kafka-console-consumer.sh` shows no error, expectedly printing `null` as value

**Comment by edenhill** [comment]
Thanks!
Try it now.

**Comment by ibalashov** [comment]
Wow, that was quick :)
Works fine now, thanks for the fix!
