### ISSUE TITLE
Consume schema id from kafkacat

### ISSUE THREAD

**Issue by rao2100** [edenhill/kafkacat#311]
Using kafka-json-schema-console-consumer i am able to get schema id with the following flag:
--property print.schema.ids=true

Does kafkacat support something similar?

**Comment by edenhill** [comment]
Added `value_schema_id` and `key_schema_id` for avro consumer in -J mode (requires my libyajl fork).

**Comment by Hubbitus** [comment]
@edenhill, could you please then provide the new release and docker image tag?

**Comment by Hubbitus** [comment]
And will it be possible to add also text %-formatters, not only for JSON output?

**Comment by edenhill** [comment]
I'll make a new release soon.

> And will it be possible to add also text %-formatters, not only for JSON output?

No, JSON only.

**Comment by edenhill** [comment]
JSON provides the structured output that's suitable for metadata information, such as schema id.

I'll try to find a better alternative to my fork of yajl.

**Comment by rao2100** [comment]
Thank very you much =)
