### ISSUE TITLE
SASL/SCRAM timeouts with 5 sec. Add -m flag to documentation / readme.

### ISSUE THREAD

**Issue by AkselAllas** [edenhill/kafkacat#317]
I'm using `-X security.protocol=SASL_SSL -X sasl.mechanism=SCRAM-SHA-512`

To fix my use case I needed to add `-m 10`. This could be documented better. I read it from a commit message.
Is this normal, that SASL SCRAM takes longer?

For querying metadata, I get the correct response, but I also get this error concatenated at the end:

```
%3|1619095255.799|FAIL|rdkafka#producer-1| [thrd:sasl_ssl://b-3.msk-2-7-0-aws.kafkaDNSaddress.]: sasl_ssl://b-3.msk-2-7-0-aws.kafkaDNSaddress/3: SASL authentication error: SaslAuthenticateRequest failed: Local: Broker handle destroyed (after 0ms in state DOWN)
```

I'm using AWS MSK default configs.

Is this error normal?

**Comment by AkselAllas** [comment]
I think the error is fine, since I listed all 3 brokers instead of one.

**Comment by edenhill** [comment]
Will improve error message.
