### ISSUE TITLE
Kerberos ticket refresh failed

### ISSUE THREAD

**Issue by akanzari** [edenhill/kafkacat#321]
when i am running below command , it is throwing error:

` sudo docker run --tty confluentinc/cp-kafkacat kafkacat -b kafka:6668 -L -X security.protocol=SASL_SSL -X sasl.kerberos.keytab="/opt/applications/dev_SP.keytab" -X sasl.kerberos.principal="dev_SP@BIGEYS.PRIV" -X sasl.kerberos.service.name="kafka"`

```
kinit: Invalid UID in persistent keyring name while getting default ccache
kinit: Invalid UID in persistent keyring name while getting default ccache
%3|1621433168.491|SASLREFRESH|rdkafka#producer-1| [thrd:app]: Kerberos ticket refresh failed: kinit -R -t "/opt/applications/dev_SP.keytab" -k dev_SP@BIGEYS.PRIV || kinit -t "/opt/applications/dev_SP.keytab" -k dev_SP@BIGEYS.PRIV: exited with code 1
```

**Comment by edenhill** [comment]
"kinit: " .. indicates it is a kerberos issue, you'll need to troubleshoot that separately.

**Comment by AC-ys** [comment]
@edenhill would you please suggest a way to troubleshoot it ? I have a similar error.

**Comment by edenhill** [comment]
Sorry no, Kerberos is a mystery. I'd just google those kinit error messages to begin with.
