### ISSUE TITLE
Security protocols

### ISSUE THREAD

**Issue by arthur-mts** [edenhill/kafkacat#329]
Can i consume a topic with security protocols? Like a topic with a sasl security mechanism?

**Comment by ALeyshon** [comment]
`kafkacat -X security.protocol=ssl` and various other protocol options exist:

Current options are `plaintext, ssl, sasl_plaintext, sasl_ssl`

https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md 🙂

**Comment by arthur-mts** [comment]
Nice! I could consume the authenticated topic with these parameters:
kafkacat -C -b $url -e -t $topic -s value=avro -s key=s -r $avro_url \
	-X sasl.mechanism=SCRAM-SHA-512 \
	-X security.protocol=SASL_SSL \
	-X sasl.username=login \
	-X sasl.password=pass
