### ISSUE TITLE
`kafkacat -C` ignores new partitions

### ISSUE THREAD

**Issue by ibalashov** [edenhill/kafkacat#35]
Once `kafkacat -C` is started it only prints messages from partitions which existed at time it was started. Newly added partitions are not included in kafkacat output(although, there is a warning that partition count changed).

It might be helpful if kafkacat could add new partitions to the output without restart.

**Comment by edenhill** [comment]
This must be a rather rare case, but interesting nontheless.
To fix this librdkafka must implement an event interface, which has been discussed previously.
Might be a good time to look into that in a couple of weeks.

**Comment by edenhill** [comment]
The -G mode should now pick up on new topics
