### ISSUE TITLE
kafkacat showing different ISR list vs other tools

### ISSUE THREAD

**Issue by wushujames** [edenhill/kafkacat#40]
For one of my topics, kafkacat is showing a different list of isrs than both the kafka-topics.sh script and kafkat (the AirBnb tool). I'm wondering if there is a bug in kafkacat.

See below, partition 1 shows isrs = 4 when using kafkacat, but isrs = 4,2,3 when using the others.

```
jcheng:~ jcheng$ docker run --rm -it kafkacat kafkacat -L -b 10.100.222.65 -t engrcloud.core.kafka.install-test
Metadata for engrcloud.core.kafka.install-test (from broker -1: 10.100.222.65:9092/bootstrap):
 5 brokers:
  broker 5 at 10.100.222.69:9092
  broker 1 at 10.100.222.65:9092
  broker 2 at 10.100.222.66:9092
  broker 3 at 10.100.222.67:9092
  broker 4 at 10.100.222.68:9092
 1 topics:
  topic "engrcloud.core.kafka.install-test" with 3 partitions:
    partition 2, leader 5, replicas: 5,3,4, isrs: 4,5,3
    partition 1, leader 4, replicas: 4,2,3, isrs: 4
    partition 0, leader 3, replicas: 3,1,2, isrs: 1,2,3
```
vs
```
jcheng:~ jcheng$ docker run --rm -it wurstmeister/kafka /opt/kafka_2.10-0.8.2.1/bin/kafka-topics.sh --zookeeper=10.100.222.69:2181 --describe --topic engrcloud.core.kafka.install-test
Topic:engrcloud.core.kafka.install-test	PartitionCount:3	ReplicationFactor:3	Configs:
	Topic: engrcloud.core.kafka.install-test	Partition: 0	Leader: 3	Replicas: 3,1,2	Isr: 1,2,3
	Topic: engrcloud.core.kafka.install-test	Partition: 1	Leader: 4	Replicas: 4,2,3	Isr: 4,2,3
	Topic: engrcloud.core.kafka.install-test	Partition: 2	Leader: 5	Replicas: 5,3,4	Isr: 4,5,3
```
vs
```
jcheng:~ jcheng$ docker run -it --rm kafkat sh -c 'echo { \"zk_path\": \"10.100.222.65:2181\" } > /etc/kafkatcfg; kafkat partitions engrcloud.core.kafka.install-test'
Topic		Partition	Leader		Replicas						ISRs
engrcloud.core.kafka.install-test0		3		[3, 1, 2]						[1, 2, 3]
engrcloud.core.kafka.install-test1		4		[4, 2, 3]						[4, 2, 3]
engrcloud.core.kafka.install-test2		5		[5, 3, 4]						[4, 5, 3]
```

Is there any debugging that I can supply?

**Comment by fsaintjacques** [comment]
This is a kafka broker known bug see https://issues.apache.org/jira/browse/KAFKA-1367

**Comment by wushujames** [comment]
Ah, thanks. From reading KAFKA-1367, it sounds like the ISR being returned from kafkacat (via the TopicMetadataResponse) is stale. So does that mean that I can trust kafka-topics.sh that my ISR list is complete?

Also, side question so I can understand better: Does kafkacat only talk to the broker? Does kafkacat talk to Zookeeper at all?

**Comment by edenhill** [comment]
@wushujames kafkacat only talks to the broker, but I guess it would make sense to add zookeeper integration for gathering information like this.

**Comment by fsaintjacques** [comment]
@edenhill aren't they fixing it (or at least thinking of fixing it)?

**Comment by edenhill** [comment]
@fsaintjacques Yeah, from what I understand they are attempting to fix it.
