### ISSUE TITLE
Build against 0.7 with reduced functionality

### ISSUE THREAD

**Issue by rrva** [edenhill/kafkacat#43]
Hi.

Is it possible to build a kafkacat for kafka 0.7 with reduced functionality?

**Comment by edenhill** [comment]
I guess it would be possible to build kafkacat with librdkafka 0.7, but some functionaltiy will probably be missing.

What is the functionality you need?

**Comment by rrva** [comment]
For now just producing messages to a single topic, to be used as a demo/troubleshooting tool.

**Comment by rrva** [comment]
+1 for possibility to create a static binary

**Comment by rrva** [comment]
But, if it's hard just skip it. We are considering to move to kafka 0.8 in a few months, depending on how much trouble that will be. I can also write something using your examples from 0.7 if that is quicker.

**Comment by edenhill** [comment]
I think you should be fine with rdkafka_example from the 0.7 branch.
