### ISSUE TITLE
kafkacat will discard some messages when the message has the char '\n'

### ISSUE THREAD

**Issue by wangmuling** [edenhill/kafkacat#44]
Hi,I have used the kafkacat for a long time,but I find a error recently.
I hava some example messages,see below:
   0xxxxxxxxxxxx
   1xxxx\nxxxxx\n
   2xxxx\nxxxxx\n
   3xxxx\nxxxxx\n

when I produce the messages  with kafkacat  and then I consume the messages with kafkacat,I find some messages have been discarded.what's you advice here?Thanks.

**Comment by fsaintjacques** [comment]
this should result in 7 messages since kafkacat split on the `\n` delimiter by default. It is your responsibility to sanitize input before sending it to kafkacat, either by replacing the in-messages new line or using another delimiter (you won't be able to use text file as input).

**Comment by edenhill** [comment]
@wangmuling Is this still an issue?

**Comment by wangmuling** [comment]
@edenhil this issue has sloved.thanks!
