### ISSUE TITLE
Loadbalancing messages between kafkacat consumers

### ISSUE THREAD

**Issue by PavelVanecek** [edenhill/kafkacat#48]
Hello,

I am attempting to use Kafka in the loadbalancing fashion. As [Kafka documentation says](http://kafka.apache.org/documentation.html#intro_consumers):

> If all the consumer instances have the same consumer group, then this works just like a traditional queue balancing load over the consumers.

So what I did is:
- Run Kafka 0.8.2.1 using [spotify/kafka](https://github.com/spotify/docker-kafka) (via boot2docker)
- Once producer
- Two consumers with same `group.id`

First I created the topic:

    $KAFKA_HOME/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 2 --topic beta

Then subscribe two consumers to it:

    kafkacat -C -b $(boot2docker ip):9092 -t beta -X group.id=mygroupid

And produce a message:

    date | kafkacat -P -b $(boot2docker ip):9092 -t beta

I expect to only one of the consumers to receive the message, but both do.

On the other hand, if I run the consumers using `kafka-console-consumer.sh`, the message is only consumed once:

    echo "group.id=mygroupid" > /consumer.beta.properties

    $KAFKA_HOME/bin/kafka-console-consumer.sh \
      --zookeeper localhost:2181 \
      --topic beta \
      --consumer.config /consumer.beta.properties

What's wrong?

(I have also asked [this question on Stackoverflow](http://stackoverflow.com/questions/32781142/sharing-messages-between-kafkacat-consumers))

**Comment by fsaintjacques** [comment]
See this issue https://github.com/edenhill/librdkafka/issues/152 . Short answer, this is not supported for now.

**Comment by PavelVanecek** [comment]
I see. Thanks for the info.
