### ISSUE TITLE
kafkacat from brew on OSX works... but displays errors

### ISSUE THREAD

**Issue by llamahunter** [edenhill/kafkacat#51]
This is probably a brew issue somehow, but when I run 

<pre class="shell">
kafkacat -L -b 10.223.25.68:9092
</pre>

Against my 5 broker cluster, I get

<pre>
Metadata for all topics (from broker -1: 10.223.25.68:9092/bootstrap):
 5 brokers:
  broker 5 at 10.223.25.69:9092
  broker 1 at 10.223.25.65:9092
  broker 2 at 10.223.25.66:9092
  broker 3 at 10.223.25.67:9092
  broker 4 at 10.223.25.68:9092
 58 topics:

... much topic metadata elided ...

%3|1445369634.430|FAIL|rdkafka#producer-0| 10.223.25.69:9092/5: Failed to connect to broker at 10.223.25.69:9092: Undefined error: 0
%3|1445369634.430|FAIL|rdkafka#producer-0| 10.223.25.68:9092/4: Failed to connect to broker at 10.223.25.68:9092: Undefined error: 0
%3|1445369634.430|ERROR|rdkafka#producer-0| 10.223.25.69:9092/5: Failed to connect to broker at 10.223.25.69:9092: Undefined error: 0
%3|1445369634.430|ERROR|rdkafka#producer-0| 10.223.25.68:9092/4: Failed to connect to broker at 10.223.25.68:9092: Undefined error: 0
%3|1445369634.430|FAIL|rdkafka#producer-0| 10.223.25.67:9092/3: Failed to connect to broker at 10.223.25.67:9092: Undefined error: 0
%3|1445369634.430|FAIL|rdkafka#producer-0| 10.223.25.66:9092/2: Failed to connect to broker at 10.223.25.66:9092: Undefined error: 0
%3|1445369634.430|ERROR|rdkafka#producer-0| 10.223.25.67:9092/3: Failed to connect to broker at 10.223.25.67:9092: Undefined error: 0
%3|1445369634.430|ERROR|rdkafka#producer-0| 10.223.25.66:9092/2: Failed to connect to broker at 10.223.25.66:9092: Undefined error: 0
%3|1445369634.430|FAIL|rdkafka#producer-0| 10.223.25.65:9092/1: Failed to connect to broker at 10.223.25.65:9092: Undefined error: 0
%3|1445369634.430|ERROR|rdkafka#producer-0| 10.223.25.65:9092/1: Failed to connect to broker at 10.223.25.65:9092: Undefined error: 0
</pre>

Those 'Undefined errors' at the end are weird.  It's clearly contacting the brokers, as it's getting the metadata.  When I run kafkacat on ubuntu against the same broker. Everything is printed out identically, except the errors aren't printed on the end.

**Comment by edenhill** [comment]
Are those errors only reported once (one FAIL and one ERROR line) per broker?
And does this happen just prior to kafkacat returning?

I'm guessing it might be termination of kafkacat (and librdkafka) that interrupts the broker threads while connecting, somehow loosing out on the proper error code.

**Comment by llamahunter** [comment]
Yes, that's the entire output of kafkacat (except all the elided topic metadata).  The errors get printed out just prior to exit when running the homebrew version on OSX, but don't get printed out when running the ubuntu .deb installed version.

A coworker who built kafkacat from github source and runs on OSX says he doesn't see these errors.  So, perhaps something is wrong with the brew recipe.
