### ISSUE TITLE
can you put in the documentation how to send to kafka a command to delete a key ?(in a compact topic)

### ISSUE THREAD

**Issue by clescot** [edenhill/kafkacat#52]
i use the compact retention policy on some topics.
i need to send to kafka, a command to add a key and no message (null payload), to create a tombstone.
i've tried this command : 
kafkacat -b <my kafka broker> -t <my-compact-topic> -p 0 -K# -c 1 -P

with input for example : 
11#
=> does it creates a tombstone?
i've seen the -Z flag, but it seems to be for a null key and not a null value .
if you can clarify this in your documentaiton, it will help many topic compact users.

best regards,

Charles.

**Comment by ecksun** [comment]
echo "abc:" | kafkacat -b localhost -t test -Z -K:

Will produce a tombstone event, you can see that with

    kafkacat -C -b localhost -t test -Z

I had the same issue as you, but my problem was that I listened for the event with `-J`, that is a JSON envelope, and that did not support outputing value as null.

I talked to @edenhill about this in gitter and he said he would fix that, and after that is fixed I do think the information you get from `--help` might be good enough, perhaps adding an example to the README.md might be in order (if this issue isn't)
