### ISSUE TITLE
Persistent metadata cache

### ISSUE THREAD

**Issue by rotac** [edenhill/kafkacat#55]
From librdkafka configuration guide:

> The metadata is automatically refreshed on error and connect.

On each kafkacat run, librdkafka loads the Kafka cluster metadata. This has a significant inbound traffic impact in situations where kafkacat is triggered frequently on a cluster with many highly partitioned topics.

Is there a way to cache the metadata in between kafkacat runs so that each kafkacat run doesn't always load a significant amount of metadata on start?

**Comment by edenhill** [comment]
How many brokers, topics and partitions do you have in your cluster? (or: `kafkacat -b .. -L | wc -l`)

Which version of kafkacat and what version of librdkafka are you using? (or `kafkacat | grep Version`)

**Comment by rotac** [comment]
We have 3 brokers in our test cluster, 5 topics each with 900 partitions. 
librdkafka 0.9.0 and we build kafkacat from master 3 days ago

**Comment by rotac** [comment]
Here is iftop report (taken on client) from one of the test runs where we were triggering millions of kafkacat runs with concurrency ~200 and small random messages. 

The amount of metadata transmitted during the test (RX) is much bigger than the amount of data sent to the cluster (TX). This is what makes me curious about the metadata caching possibilities.

![network-client](https://cloud.githubusercontent.com/assets/578137/11745551/483f3f7a-a019-11e5-99b1-a95878caf74f.jpg)

**Comment by edenhill** [comment]
Ah, ok, I understand.

There is currently no way to cache the metadata, but it is an interesting proposal which could also be useful for other scenarios (NAT/firewall traversal for instance).

But are you sure executing kafkacat once for each message is the best way to go, wouldn't a more persist program be more suitable for this?
Have you looked at [bruce](https://github.com/ifwe/bruce) ?

Alternatively you could use [kafka-rest](https://github.com/confluentinc/kafka-rest)

**Comment by rotac** [comment]
I agree, producer daemon like Bruce might be a better fit for our use case. Yet the kafkacat ease of use,  statelessness and performance appeals to me.

We have tested Bruce too, with following remarks:
1. Bruce drops messages (documented behavior yet hard to avoid).
2. Bruce has small max. buffer size.
3. Bruce has a fairly small max. message size ~425KB.
4. After whole day of Bruce tuning we were not able to outperform kafkacat for our test case.

Let me know if you choose to implement the persistent metadata cache, maybe I can lend a hand somehow (e.g. testing, as I'm not good enough at C).

**Comment by edenhill** [comment]
Thanks for sharing you reasoning and offering to help, both very valuable resources :)

Let me know what you think of this proposal:
 * Add a `--metadata-cache <path.json>` option to kafkacat, rest of the points assume option is provided.
 * Cache is the JSON representation of the metadata (same as `kafkacat -L -k -J ..`)
 * If cache file exists use that instead instead of querying brokers' for metadata and turn off periodic metadata refresh, else query as usual.
 * In case of produce/fetch error, in particular the ones pointing out broker is not leader for given partition, refresh metadata from broker.
 * On exit, write latest known metadata to cache file.

**Comment by rotac** [comment]
Sounds great! 

1. When process starts, it might be better check the age of the cached metadata file content. Maybe you can use topic.metadata.refresh.interval.ms in that check? 

2. In case of many concurrent kafkacat processes, I can imagine multiple processes attempting to refresh the metadata file at the very same moment (e.g. after Kafka node drops out of cluster).

2a. I think there might be a need for write lock on such file during the refresh process. 
2b. Also, if the file is already locked other processes don't need to fetch the metadata. Those processes can wait for the first process to finish the refresh, no? Again, not a pro...

**Comment by edenhill** [comment]
For **1.**: It doesn't really matter if the cache is old, if it turns out to be outdated and incorrect it will simply trigger a refresh of the metadata.

Good points regarding locking (which is a bit painful on the porting front unfortunately).

**Comment by rotac** [comment]
You are right, refresh on error is certainly enough.

**Comment by edenhill** [comment]
This is quite alot of work for a pretty specific use-case, marking as wontfix for now.
