### ISSUE TITLE
kafkacat -c -NUM semantics edge case

### ISSUE THREAD

**Issue by cavanaug** [edenhill/kafkacat#56]
Here is the use-case.     A topic with say 150 messages.   

$kafkacat -b broker -C -q -o -1000 -e -c 1000 -t topic | wc -l
0

$kafkacat -b broker -C -q -o -100 -e -c 1000 -t topic | wc -l
100

What this shows is that if the negative offset is larger than available it doesnt return anything.    Semantically I believe this should just return from the beginning then.

**Comment by edenhill** [comment]
Hey,

I can't reproduce this on latest kafkacat master (with latest librdkafka master).
What version are you on?


````
maglun@bib:~$ kafkacat -b localhost -q -o beginning -e -t newt2 | wc -l
100
maglun@bib:~$ kafkacat -b localhost -q -o -1000 -e -c 1000 -t newt2 | wc -l
100
maglun@bib:~$ kafkacat -b localhost -q -o -75 -e -c 1000 -t newt2 | wc -l
75
````

**Comment by cavanaug** [comment]
It was the 1.2 version.    I just tried pulling the head from git but got
compile errors on Centos 6.

....
mp-bootstrap/usr/local/lib/librdkafka.a(rdkafka_sasl.o): In function
`rd_kafka_sasl_handle_recv':
/net/san-hdp-gateway-1/local/disk1/home/cavanaug/src_internet/git_src/kafkacat/tmp-bootstrap/librdkafka/src/rdkafka_sasl.c:118:
undefined reference to `sasl_client_step'
/net/san-hdp-gateway-1/local/disk1/home/cavanaug/src_internet/git_src/kafkacat/tmp-bootstrap/librdkafka/src/rdkafka_sasl.c:151:
undefined reference to `sasl_errdetail'
/net/san-hdp-gateway-1/local/disk1/home/cavanaug/src_internet/git_src/kafkacat/tmp-bootstrap/librdkafka/src/rdkafka_sasl.c:118:
undefined reference to `sasl_client_step'
/net/san-hdp-gateway-1/local/disk1/home/cavanaug/src_internet/git_src/kafkacat/tmp-bootstrap/librdkafka/src/rdkafka_sasl.c:163:
undefined reference to `sasl_getprop'
/net/san-hdp-gateway-1/local/disk1/home/cavanaug/src_internet/git_src/kafkacat/tmp-bootstrap/librdkafka/src/rdkafka_sasl.c:167:
undefined reference to `sasl_getprop'
/net/san-hdp-gateway-1/local/disk1/home/cavanaug/src_internet/git_src/kafkacat/tmp-bootstrap/librdkafka/src/rdkafka_sasl.c:171:
undefined reference to `sasl_getprop'
tmp-bootstrap/usr/local/lib/librdkafka.a(rdkafka_sasl.o): In function
`rd_kafka_sasl_global_term':
/net/san-hdp-gateway-1/local/disk1/home/cavanaug/src_internet/git_src/kafkacat/tmp-bootstrap/librdkafka/src/rdkafka_sasl.c:545:
undefined reference to `sasl_done'
collect2: ld returned 1 exit status
make: *** [kafkacat] Error 1
┌─[✗]─[19:27:06]─[cavanaug@san-hdp-gateway-1
:~/src_internet/git_src/kafkacat]

**Comment by edenhill** [comment]
That's a librdkafka build issue, it seems to find the sasl headers but not the library.
Could you try installing the `cyrus-sasl-devel` and possibly `cyrus-sasl-2` ?
