### ISSUE TITLE
Kafkacat loops and consume all bandwidth

### ISSUE THREAD

**Issue by josselin-c** [edenhill/kafkacat#58]
Hello,

When kafkacat tries to fetch a message bigger than librdkafka fetch.message.max.bytes, kafkacat loops forever and consumes all bandwidth and cpu.

Instead it should throttle / print a message / return?

**Comment by edenhill** [comment]
Yes, that's a feature and allows kafkacat to be used as a network load test tool.

**Comment by edenhill** [comment]
Created upstream bug here:
https://github.com/edenhill/librdkafka/issues/482

**Comment by josselin-c** [comment]
@edenhill thanks =)

**Comment by edenhill** [comment]
Fixed in librdkafka 0.9.2
