### ISSUE TITLE
/usr/bin/ld: cannot find -lyajl 

### ISSUE THREAD

**Issue by giaosudau** [edenhill/kafkacat#59]
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

sudo ldconfig -p | grep yajl
`libyajl.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyajl.so.2
libyajl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libyajl.so`

**Comment by edenhill** [comment]
What does   ldd kafkacat   tell you?

**Comment by giaosudau** [comment]
@edenhill 
```
$ make
Creating program kafkacat
gcc -Itmp-bootstrap/usr/local/include -g -O2 -Wall -Wfloat-equal -Wpointer-arith -Itmp-bootstrap/usr/local/include -g -O2 -Wall -Wfloat-equal -Wpointer-arith  kafkacat.o format.o json.o -o kafkacat -L/usr/local/lib  -lpthread -lz -lssl -lcrypto -lsasl2 -lrt   tmp-bootstrap/usr/local/lib/librdkafka.a -Wl,-Bstatic -lyajl -Wl,-Bdynamic -L/usr/local/lib  -lpthread -lz -lssl -lcrypto -lsasl2 -lrt   tmp-bootstrap/usr/local/lib/librdkafka.a -Wl,-Bstatic -lyajl -Wl,-Bdynamic
/usr/bin/ld: cannot find -lyajl
collect2: error: ld returned 1 exit status
make: *** [kafkacat] Error 1
```
It's stuck in make step and can't make install
I don't know what you mean `ldd kafkacat`.

**Comment by vincentbernat** [comment]
I think it is looking at libyajl.a (due to requesting static linking). Dunno why static linking was requested, I don't know enough about mklove.

**Comment by edenhill** [comment]
That's the ootstrap script that links both librdkafka and libyajl statically.

@giaosudau  But I think you are using an older version of kafkacat, can you update to latest master, remove tmp-bootstrap, and try again?

**Comment by giaosudau** [comment]
@edenhill I clone from master branch today.

**Comment by edenhill** [comment]
Are you running ./bootstrap.sh or ./configure + make?

**Comment by tukushan** [comment]
I got this problem running the ./bootstrap.sh

> ...
> Creating program kafkacat
> gcc  -Itmp-bootstrap/usr/local/include -Itmp-bootstrap/usr/local/include -g -O2 -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wcast-align  kafkacat.o format.o tools.o json.o -o kafkacat  -L/usr/local/lib  -lpthread -lz -lcrypto -lssl -lsasl2 -lrt -ldl   -Wl,-Bstatic -lyajl -Wl,-Bdynamic tmp-bootstrap/usr/local/lib/librdkafka.a  -L/usr/local/lib  -lpthread -lz -lcrypto -lssl -lsasl2 -lrt -ldl  
> /usr/bin/ld: cannot find -lyajl
> collect2: error: ld returned 1 exit status
> mklove/Makefile.base:134: recipe for target 'kafkacat' failed
> make: *** [kafkacat] Error 1
>
