### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by bric3** [edenhill/kafkacat#61]
Kafka new consumer support would be great, but the released version is only 1.2.0
Is it possible to release a beta or a release candidate ?

**Comment by edenhill** [comment]
My plan is to roll a 0.9.1 release of librdkafka soon and will have kafkacat follow shortly.

**Comment by bric3** [comment]
Cool, I'm looking forward the update :)
I saw the [wip1](https://github.com/edenhill/librdkafka/releases/tag/0.9.1-wip1) release but thought there was significant updates in 0.9.0.99, that's why I was wondering on a release. Especially since Kafka authors has launched today the vote for (0.10](http://mail-archives.apache.org/mod_mbox/kafka-users/201603.mbox/%3CCAA9QSJKv08tUBy1nFCOZirqK2qjuNBAQxA19Cv6oM6xKJ5YLVQ%40mail.gmail.com%3E).

**Comment by edenhill** [comment]
The 0.9.1 release will not support the new stuff in 0.10.0, but it will be shortly followed by a release that does.

**Comment by tcrayford** [comment]
@edenhill will this include SSL support, or is that already included? I tried to pass `-X 'security.protocol=ssl'` and got an error back about that property not existing.

**Comment by edenhill** [comment]
@tcrayford Both SSL and SASL are configuration-only features of librdkafka so they dont depend on specific support in kafkacat, all you need to do is build librdkafka with SSL support (enabled by default if libssl-dev is found) and install it.

**Comment by tcrayford** [comment]
@edenhill ok, thanks. I will try and make sure OSX's homebrew has the new librdkafka soonish (it only has 0.8.6 right now).

**Comment by edenhill** [comment]
@tcrayford I'll release librdkafka 0.9.1 soon, you should wait for that before rolling a new homebrew release.

**Comment by tcrayford** [comment]
@edenhill fair (for the record I am not a maintainer of homebrew or librdkafka, but I am sure homebrew will take a PR)

**Comment by uhoh-itsmaciek** [comment]
@edenhill it seems the deb package does *not* support SSL--is that correct? I need to build from source if I want SSL support?

**Comment by edenhill** [comment]
@uhoh-itsmaciek Since SSL is specific to the librdkafka package, not kafkacat, it depends on which librdkafka package you have installed.
I believe there is no official Debian or Ubuntu package for librdkafka >=0.9 yet, which is required for SSL support.
What you can do is either build your own librdkafka package off master, or simply build kafkacat with with the ./bootstrap.sh script to have it pull in and link the latest version of librdkafka automatically - make sure to install libssl-dev first though so that librdkafka's configure will pick up SSL support.

**Comment by uhoh-itsmaciek** [comment]
Got it, thanks!

**Comment by neverfox** [comment]
I saw that librdkafka moved to 0.9.1 today. Any chance that 1.3.0 update is coming on the heels?

**Comment by edenhill** [comment]
1.3.0 was released last week :)

**Comment by neverfox** [comment]
@edenhill Sorry, I should have been more specific. I meant on homebrew. I guess it just needs a pull request over there.

**Comment by neverfox** [comment]
@edenhill I have submitted the PR to homebrew-core.

**Comment by konobi** [comment]
Currently it appears that using bootstrap.sh with a current and fresh checkout leads to a build with no SSL as protocol support. Does the script need updated somehow?

**Comment by edenhill** [comment]
@konobi The bootstrap script depends on OpenSSL devel packages being installed on the build host, it is not automatically downloaded and built by the bootstrap script since openssl is considered a standard library.

**Comment by konobi** [comment]
The libraries are installed and the rdkafka config shows as ssl 'y'. is there a missing object file that needs added to the config?

**Comment by edenhill** [comment]
Try  `kafkacat -X builtin.features=ssl`, is it saying that's an unknown value or does it just give you the usage printout?

**Comment by konobi** [comment]
unknown value =0/

**Comment by edenhill** [comment]
Very weird, can you paste tmp-bootstrap/librdkafka/config.log?

**Comment by konobi** [comment]
Copy here: https://gist.github.com/konobi/ff303ca6998a3e68d3ce44fa0dd3ed12

**Comment by edenhill** [comment]
```
DBG: compile check for libssl (WITH_SSL) failed: gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wall -Werror -lssl _mkltmprucZeY.c -o _mkltmprucZeY.c.o  : /usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status
DBG: Check libssl (WITH_SSL, action disable (originally disable)) failed: compile check failed:
CC: CC
flags: -lssl
gcc  -g -O2 -fPIC -Wall -Wsign-compare -Wfloat-equal -Wpointer-arith -Wall -Werror -lssl _mkltmprucZeY.c -o _mkltmprucZeY.c.o  :
/usr/bin/ld: cannot find -lssl
```

It cant find the SSL library. (nonstandard location?)

**Comment by konobi** [comment]
no, it's in the standard location on debian jessie.

**Comment by edenhill** [comment]
Are you sure you have libssl-dev installed?
Try this:
```
 echo "" > /tmp/x.c
 gcc /tmp/x.c -o /tmp/x -lssl
```

It should complain about missing main symbol, but not missing -lssl library

**Comment by konobi** [comment]
mkay... I have it in a more reasonable state now. ssl-dev was missing, as is sasl-dev... but all rather confusing.

**Comment by edenhill** [comment]
It'll need the -dev packages to build, the non -dev packages are only for already built/linked applications.

**Comment by konobi** [comment]
Yup, I have it working and appearing in features now. But just no documentation on how to connect to an SSL server =0(

**Comment by edenhill** [comment]
https://github.com/edenhill/librdkafka/wiki/Using-SSL-with-librdkafka

**Comment by ratemyduck** [comment]
I've read the thread ... when will SSL support come? Would you like a PR?

**Comment by edenhill** [comment]
@ratemyduck SSL is already supported, you just need to make sure libssl-dev and libsasl2-dev (for SASL) is installed prior to building librdkafka.
But the easiest way is to install librdkafka from the Confluent APT repository which will ensure you always have the latest version: http://docs.confluent.io/current/installation.html#installation-apt

**Comment by ratemyduck** [comment]
@edenhill Why should I have to build librdkafka to use SSL with Kafkacat? It's too much of a hassle. It should be done when the vanilla container is created. I should just pull the container, it SSL/SASL support should be there. Think some dude in my company kinda did it, and I can port that here, to this repo. Would you like me to?

**Comment by edenhill** [comment]
@ratemyduck kafkacat does not implement the Kafka protocol itself, but depens on librdkafka to do that. librdkafka in turn does not implement SSL, SASL Kerberos, zlib compression, etc itself, but depends on 3rd party libraries such as OpenSSL, Cyrus-SASL, zlib, etc.
So if you want to use SSL with Kafkacat, you need to make sure that the underlying librdkafka library has support for SSL. And this is typically as easy as installing the Confluent deb/rpm packages, or using `homebrew install librdkafka` on OSX.
If none of those approaches apply to your platform you will need to build librdkafka yourself, which is outlined in the librdkafka README file but boils down to: install dependencies (libssl-dev, etc), ./configure, make, sudo make install.

As for containers: I'm not providing a kafkacat docker image, I rely on the community to do that.
Search google for "docker kafkacat" and you should find a bunch.

**Comment by ratemyduck** [comment]
Ah, sorry thought you were the maintainer of docker image too ... Ahhh,
sorry. I'm one confused puppy. And thanks for your patience with me.



2017-09-03 8:28 GMT+02:00 Magnus Edenhill <notifications@github.com>:
