### ISSUE TITLE
support for zookeeper.connect chroot path

### ISSUE THREAD

**Issue by TinLe** [edenhill/kafkacat#62]
This probably should be filed against both librdkafka and kafkacat.   This is an enhancement request.

[http://kafka.apache.org/08/documentation.html|(http://kafka.apache.org/08/documentation.html)]

Documentation describes.

_zookeeper.connect_

> Zookeeper also allows you to add a "chroot" path which will make all kafka data for this cluster appear under a particular path. This is a way to setup multiple Kafka clusters or other applications on the same zookeeper cluster. To do this give a connection string in the form hostname1:port1,hostname2:port2,hostname3:port3/chroot/path which would put all this cluster's data under the path /chroot/path. Note that you must create this path yourself prior to starting the broker and consumers must use the same connection string.

**Comment by fsaintjacques** [comment]
IIRC, kafkacat/librdkafka don't talk to zookeeper.

**Comment by TinLe** [comment]
That's what the broker is :-)

**Comment by fsaintjacques** [comment]
But with kafka 0.9, there's no need for the consumer/producer to talk to zookeeper. If you look kafkacat doesn't reference zookeeper once.

**Comment by TinLe** [comment]
Sure, some small places don't use it.  But enterprises do use it.   We have very large infrastructure.   Currently kafkacat is not working with that.  We wrote a go kafkacat look alike that supports zookeeper, schemaserver and so on.   Let me see if we can open source it.

**Comment by fsaintjacques** [comment]
Maybe the issue you opened isn't what you want? kafkacat has no support for zookeeper, thus it is pointless to open an issue to update the documentation regarding `zookeeper.connect` configuration.

If you want baked-in support for zookeeper, that's another matter.

**Comment by edenhill** [comment]
@TinLe The reliance on Zookeeper for Apache Kafka clients was a 0.7-0.8 thing, with 0.9 a client no longer needs to talk to zookeeper at all.

**Comment by wujiang157** [comment]
whether librdkafka support  to config chroot path,  producer set its  chroot path as  /kafka   , how consumer set  chroot  path value

**Comment by edenhill** [comment]
Neither librdkafka or kafkacat supports ZooKeeper, and won't. Clients should talk directly to Kafka, not through ZK.
