### ISSUE TITLE
Added metadata-list for consumergroups 

### ISSUE THREAD

**Issue by FDePourcq** [edenhill/kafkacat#63]
- removed high-level-consumer as a mode.
      downgraded -G to -g as a switch in -C and -L modes.
    - added metadata-list mode for consumergroups
      with retrieval of watermarks and stored offsets.

[kafkacat_metadata_for_consumergroups.diff.txt](https://github.com/edenhill/kafkacat/files/219074/kafkacat_metadata_for_consumergroups.diff.txt)

**Comment by FDePourcq** [comment]
--> created pull request: https://github.com/edenhill/kafkacat/pull/64

**Comment by papa99do** [comment]
Hi @edenhill, the metadata of a consumer group is a useful piece of information. It would be nice if kafkacat can support this out of the box.
