### ISSUE TITLE
kafkacat topic info doesn't match that of kafka-topics

### ISSUE THREAD

**Issue by charity** [edenhill/kafkacat#65]
Hiya.  I'm running into something where the leader/follower/ISR reported by kafkacat doesn't match that reported by kafka-topics.

Any ideas?  Even more confusingly: I'm logged in to broker 1002/kafka900f5013 in two shells right now.  For the past hour or so kafkacat was reporting the correct information (partition 0, leader 1002, replicas: 1002, isrs: 1002) in one of the shells, and incorrect information in the other shell (partition 0, leader 1004, replicas: 1004, isrs: 1004).  Consistently and repeatedly.  It was just while I was typing up this git issue that they all started reporting the same incorrect information as the rest of the nodes.

So Kafkacat thinks the partition is being served by broker 1004:

``````
PRODUCTION ubuntu@bastion-0:~$ dsh -g kafka-production -c -M -- "kafkacat -L -b localhost:9092 -t hound-prod.retriever.mutation"
kafka-1bc7c4e2: Metadata for hound-prod.retriever.mutation (from broker -1: localhost:9092/bootstrap):
kafka-1bc7c4e2:  4 brokers:
kafka-1bc7c4e2:   broker 1003 at ip-10-0-246-113.ec2.internal:9092
kafka-1bc7c4e2:   broker 1004 at ip-10-0-190-45.ec2.internal:9092
kafka-1bc7c4e2:   broker 1001 at ip-10-0-148-52.ec2.internal:9092
kafka-1bc7c4e2:   broker 1002 at ip-10-0-207-186.ec2.internal:9092
kafka-1bc7c4e2:  1 topics:
kafka-1bc7c4e2:   topic "hound-prod.retriever.mutation" with 1 partitions:
kafka-1bc7c4e2:     partition 0, leader 1004, replicas: 1004, isrs: 1004
kafka-d4b7674e: Metadata for hound-prod.retriever.mutation (from broker -1: localhost:9092/bootstrap):
kafka-d4b7674e:  4 brokers:
kafka-d4b7674e:   broker 1003 at ip-10-0-246-113.ec2.internal:9092
kafka-d4b7674e:   broker 1004 at ip-10-0-190-45.ec2.internal:9092
kafka-d4b7674e:   broker 1001 at ip-10-0-148-52.ec2.internal:9092
kafka-d4b7674e:   broker 1002 at ip-10-0-207-186.ec2.internal:9092
kafka-d4b7674e:  1 topics:
kafka-d4b7674e:   topic "hound-prod.retriever.mutation" with 1 partitions:
kafka-d4b7674e:     partition 0, leader 1004, replicas: 1004, isrs: 1004
kafka-900f5013: Metadata for hound-prod.retriever.mutation (from broker -1: localhost:9092/bootstrap):
kafka-900f5013:  4 brokers:
kafka-900f5013:   broker 1003 at ip-10-0-246-113.ec2.internal:9092
kafka-900f5013:   broker 1004 at ip-10-0-190-45.ec2.internal:9092
kafka-900f5013:   broker 1001 at ip-10-0-148-52.ec2.internal:9092
kafka-900f5013:   broker 1002 at ip-10-0-207-186.ec2.internal:9092
kafka-900f5013:  1 topics:
kafka-900f5013:   topic "hound-prod.retriever.mutation" with 1 partitions:
kafka-900f5013:     partition 0, leader 1004, replicas: 1004, isrs: 1004
kafka-88e6bc0c: Metadata for hound-prod.retriever.mutation (from broker -1: localhost:9092/bootstrap):
kafka-88e6bc0c:  4 brokers:
kafka-88e6bc0c:   broker 1003 at ip-10-0-246-113.ec2.internal:9092
kafka-88e6bc0c:   broker 1004 at ip-10-0-190-45.ec2.internal:9092
kafka-88e6bc0c:   broker 1001 at ip-10-0-148-52.ec2.internal:9092
kafka-88e6bc0c:   broker 1002 at ip-10-0-207-186.ec2.internal:9092
kafka-88e6bc0c:  1 topics:
kafka-88e6bc0c:   topic "hound-prod.retriever.mutation" with 1 partitions:
kafka-88e6bc0c:     partition 0, leader 1004, replicas: 1004, isrs: 1004

```

And kafka-topics thinks the partition is being served by broker 1002.

```
```PRODUCTION ubuntu@bastion-0:~$ dsh -g kafka-production -c -M -- "kafka-topics --zookeeper zk1:2181,zk2:2181,zk3:2181/kafka --topic hound-prod.retriever-mutation --describe"
kafka-d4b7674e: Topic:hound-prod.retriever-mutation     PartitionCount:1        ReplicationFactor:1     Configs:
kafka-d4b7674e:         Topic: hound-prod.retriever-mutation    Partition: 0    Leader: 1002    Replicas: 1002  Isr: 1002
kafka-1bc7c4e2: Topic:hound-prod.retriever-mutation     PartitionCount:1        ReplicationFactor:1     Configs:
kafka-1bc7c4e2:         Topic: hound-prod.retriever-mutation    Partition: 0    Leader: 1002    Replicas: 1002  Isr: 1002
kafka-88e6bc0c: Topic:hound-prod.retriever-mutation     PartitionCount:1        ReplicationFactor:1     Configs:
kafka-88e6bc0c:         Topic: hound-prod.retriever-mutation    Partition: 0    Leader: 1002    Replicas: 1002  Isr: 1002
kafka-900f5013: Topic:hound-prod.retriever-mutation     PartitionCount:1        ReplicationFactor:1     Configs:
kafka-900f5013:         Topic: hound-prod.retriever-mutation    Partition: 0    Leader: 1002    Replicas: 1002  Isr: 1002
PRODUCTION ubuntu@bastion-0:~$ 
```

Any ideas?

Just looking at the data sizes on disk, it's definitely writing to broker 1002, not 1004.

**Comment by edenhill** [comment]
kafkacat uses the Kafka broker protocol's MetadataRequest to directly query the broker for cluster and topic metadata information, while kafka-topics.sh queries zookeeper for the same information.

Clearly one of those are out of sync in your printouts, and the information retrieved directly from Kafka brokers is usually authoritative (e.g., kafkacat > kafka-topics.sh), unless some of the brokers are acting up.

Could you log in to one of your broker VMs and run kafkacat once for each broker, explicitly providing `-b <broker>` for each call (where `broker` is the hostname reported in the metadata printout above, e.g.: `ip-10-0-246-113.ec2.internal:9092`)?
While this is probably exactly what dsh does, I'd like it to be a bit more explicit to rule out the case where just one of the brokers were queried.

**Comment by fsaintjacques** [comment]
Are you running with unsafe leader election?

**Comment by charity** [comment]
Found the problem -- kafka treats the "." character as a wildcard in topic names.  And kafkacat will silently create a new topic if you describe it (unlike kafka-topic --describe).  You can see in the first example, the topic is "hound-prod.retriever.mutation", and the second it is hound-prod.retriever-mutation".

Suggest making "kafkacat -D -t $topic" not create the topic if it doesn't exist, and instead behave the way "kafka-topics --topic --describe" does :)

**Comment by edenhill** [comment]
The automatic topic creation is actually a broker side feature and config (auto.create.topics.enable=true), to avoid it you can list all topics (leave out the -t ..topic.. switch) and then do output filtering (preferably with JSON / jq)
