### ISSUE TITLE
Protocol parse failure (incorrect broker.version)

### ISSUE THREAD

**Issue by agboom** [edenhill/kafkacat#67]
After upgrading to kafkacat 1.3.0 and librdkafka 0.9.1 I get the following error in consumer mode:

```
%4|1467207129.009|PROTOERR|rdkafka#consumer-1| <ip>:9092/1: Protocol parse failure at rd_kafka_fetch_reply_handle:3748 (incorrect broker.version.fallback?)
%4|1467207129.009|PROTOERR|rdkafka#consumer-1| <ip>:9092/3: Protocol parse failure at rd_kafka_fetch_reply_handle:3748 (incorrect broker.version.fallback?)
%4|1467207129.009|PROTOERR|rdkafka#consumer-1| <ip>:9092/3: expected 36681250 bytes > 150 remaining bytes
%4|1467207129.009|PROTOERR|rdkafka#consumer-1| <ip>:9092/2: Protocol parse failure at rd_kafka_fetch_reply_handle:3748 (incorrect broker.version.fallback?)
```

Any idea what this means?

**Comment by edenhill** [comment]
The Kafka protocol has grown significantly during the last year and librdkafka needs to know what the broker supports.
See this link for more info: https://github.com/edenhill/librdkafka/wiki/Broker-version-compatibility

**Comment by edenhill** [comment]
In essence you need to provide some configuration based on your broker version:
 * **broker >=0.10.0.0**: `-X api.version.request=true`
 * **all older versions**: `-X broker.version.fallback=<the.broker.version>`,   e.g. `-X broker.version.fallback=0.8.2.2`.  The default value is 0.9.0.0

**Comment by iiwaasnet** [comment]
> In essence you need to provide some configuration based on your broker version:
> 
> * **broker >=0.10.0.0**: `-X api.version.request=true`
> * **all older versions**: `-X broker.version.fallback=<the.broker.version>`,   e.g. `-X broker.version.fallback=0.8.2.2`.  The default value is 0.9.0.0

You still made my day 2 years later! :) Would it make sense to add more descriptive error info?

**Comment by AkaiNoCat** [comment]
> In essence you need to provide some configuration based on your broker version:
> 
> * **broker >=0.10.0.0**: `-X api.version.request=true`
> * **all older versions**: `-X broker.version.fallback=<the.broker.version>`,   e.g. `-X broker.version.fallback=0.8.2.2`.  The default value is 0.9.0.0

You still made my day 2 years later! :)
