### ISSUE TITLE
Getting the last X messages doesn't return any results when it overflows

### ISSUE THREAD

**Issue by filipefigcorreia** [edenhill/kafkacat#68]
The documentation says that we can ask for the last 2000 messages with the command:

> $ kafkacat -C -b mybroker -t syslog -p 0 -o -2000 -e

I find that this works really well, except when you have less that 2000 messages in the topic, in which case it returns no results. Any chance that this behaviour can be changed to include all the messages in the topic?

**Comment by edenhill** [comment]
Can you provide the output from `kafkacat -V` ?

**Comment by filipefigcorreia** [comment]
Sure. I will be away from the office until the 11th, but I will check it what's the output when I get back.

**Comment by edenhill** [comment]
Okay, let me know when you have it,.
What I'm actually after is the librdkafka version because I believe this issue was fixed in librdkafka 0.9.1

**Comment by filipefigcorreia** [comment]
It appears that I have librdkafka 0.9.1 already after all:

```
$ kafkacat -V
kafkacat - Apache Kafka producer and consumer tool
https://github.com/edenhill/kafkacat
Copyright (c) 2014-2015, Magnus Edenhill
Version KAFKACAT_VERSION (librdkafka 0.9.1)
```

But I no longer have the same test data that I had a week ago, and I'm not being able to reproduce the issue :-\

I've tried to recreate a minimal example, but it worked fine:

```
$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic atesttopic              
1
2
3
4
$ bin/kafka-console-consumer.sh --new-consumer --bootstrap-server localhost:9092 --topic atesttopic --from-beginning
1
2
3
4
$ kafkacat -C -b localhost:9092 -t atesttopic -p 0 -o -30 -e 
1
2
3
4
% Reached end of topic atesttopic [0] at offset 4: exiting
```

**Comment by edenhill** [comment]
Okay, we'll reopen this if you see it again.
Thanks
