### ISSUE TITLE
Failed to resolve broker hostname when using docker.

### ISSUE THREAD

**Issue by guillaumekoenig** [edenhill/kafkacat#69]
Hello !

I use the confluent/kafka docker image, with port 9092 exposed to the host, for testing. Querying metadata with kafkacat works fine :
```
$ kafkacat -L -b 127.0.0.1:9092
Metadata for all topics (from broker -1: 127.0.0.1:9092/bootstrap):
 1 brokers:
  broker 0 at 1cbfdb9e8dc6:9092
 3 topics:
  topic "__consumer_offsets" with 50 partitions:
    partition 23, leader 0, replicas: 0, isrs: 0
    partition 41, leader 0, replicas: 0, isrs: 0
...
```
but unfortunately not for producing or consuming messages :
```
$ echo something|kafkacat -b localhost:9092 -t my-awesome-topic
% Auto-selecting Producer mode (use -P or -C to override)
%3|1467649510.255|FAIL|rdkafka#producer-1| 1cbfdb9e8dc6:9092/0: Failed to resolve '1cbfdb9e8dc6:9092': Name or service not known
% ERROR: Local: Host resolution failure: 1cbfdb9e8dc6:9092/0: Failed to resolve '1cbfdb9e8dc6:9092': Name or service not known
```
```
$ kafkacat -b localhost:9092 -t my-awesome-topic
% Auto-selecting Consumer mode (use -P or -C to override)
%3|1467649527.523|FAIL|rdkafka#consumer-1| 1cbfdb9e8dc6:9092/0: Failed to resolve '1cbfdb9e8dc6:9092': Name or service not known
% ERROR: Local: Host resolution failure: 1cbfdb9e8dc6:9092/0: Failed to resolve '1cbfdb9e8dc6:9092': Name or service not known
```
Note that `1cbfdb9e8dc6` corresponds to the container running kafka (and it's the hostname inside the container).

It looks like when trying to consume/produce, the broker hostname from metadata is used. However, given the use of docker, that hostname is `1cbfdb9e8dc6` and cannot be contacted from the host. I tested both kafkacat linked against rdkafka 0.8.6 and kafkacat linked against rdkafka 0.9.1. Let me know I can provide you with more information.

**Comment by edenhill** [comment]
Since there is currently no way for a Kafka client to identify a broker inside an existing session it needs to be able to connect to the brokers advertised in the metadata response.

So in this case you'll need to add the docker hosts to your /etc/hosts or similar.

**Comment by guillaumekoenig** [comment]
Ok. Thank you very much for your feedback.
