### ISSUE TITLE
possible message truncation

### ISSUE THREAD

**Issue by ctramnitz** [edenhill/kafkacat#76]
I'm using socat (with multiple senders, socat is configured to fork) to pipe data into kafkcat running as producer with snappy compression enabled. Now I'm noticing some truncated messages:
original message 1: "<14> date1 process1 this is an interesting syslog message\n"
original message 2: "<14> date2 process2 and another one\n"
data in Kafka: "<14> date1 process1 this is an int<14> date2 process2 and another one\n"

Could this be related to the way I'm using kafkacat with socat (forks) or maybe max bytes kicking in in the middle of a message?

Any suggestions how to get rid of this behavior or how to troubleshoot further?

**Comment by fsaintjacques** [comment]
I'd suspect newline problem.

**Comment by ctramnitz** [comment]
If it was an extra newline (i.e. within the message) there would be more messages, not less messages. If the newline at the end of the message was missing the first message wouldn't truncated.
Actually rsyslogd is producing the messages piping into socat and it is configured to replace all control characters with "#<ascii-code>" and have a "\n" at the end of every message.

**Comment by edenhill** [comment]
When you say socat is forking and piping data to kafkacat, does that mean each fork pipes to its own kafkacat, or do they all pipe to the same kafkacat?
In the latter case I dont see a guarantee for per-line-atomicness

**Comment by ctramnitz** [comment]
I'm not sure how I could tell each fork to use its own kafkacat, we are starting it like:
socat -u tcp-listen:port,bind=127.0.0.1,fork,reuseaddr - 2>/dev/null | kafkacat -P -b <broker> -t <topic> -z snappy
With ps I can see multiple socat processes but just a single kafkacat process.

I see your point about per-line-atomicness, I already suspected it...

**Comment by ctramnitz** [comment]
will try running kafkacat directly from socat's EXEC directive instead, this should result in a kafkacat per fork
