### ISSUE TITLE
show compression if any by msg

### ISSUE THREAD

**Issue by bf228** [edenhill/kafkacat#78]
Is there a way to see what compression has been used on s message in a topic via kafkacat?  I've done a "-d all" and I don't see anything about the type of compression used (or not).

I'm troubleshooting a perl based kafka module which at times fails because its reporting the message is snappy compressed.  I dont think the messages are snappy compressed but looking for a way to validate this-- was hoping kafkacat might help.  

If compression type isn't something reportable by kafkacat, is there some other mechanism that would confirm the presences or not of snappy compression on messages in a topic?

thanks

**Comment by edenhill** [comment]
There's currently no way of seeing that.
For debugging purposes you can add a printf (or rd_rkb_dbg) somewhere around here to print hdr.Attributes (lowest 3 bits are compression codec):
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L3557

**Comment by bf31415** [comment]
thanks-- that worked and provided the insight i needed

**Comment by nitin456** [comment]
@edenhill is there any plan to support this in master ?

**Comment by edenhill** [comment]
That would need to be exposed by librdkafka, and there are no such plans since it is unclear what the use-case is.
What librdkafka could provide is a log message per MessageSet stating the compression codec.
