### ISSUE TITLE
kafkacat built using bootstrap.sh does not print message timestamps

### ISSUE THREAD

**Issue by wushujames** [edenhill/kafkacat#82]
I'm trying to build a binary of kafkacat that will let me print out message timestamps. I am downloading this github repo (as a zip file) and using bootstrap.sh to do the build. The resulting kafkacat binary does not have support for message timestamps. Do I need to pass some command-line options, or have specific libraries in my environment for this to work?

**Comment by wushujames** [comment]
See attached file of my compilation. The resulting "usage" text doesn't list the option to display message timestamps (%T)

[kafkacat.txt](https://github.com/edenhill/kafkacat/files/658575/kafkacat.txt)

**Comment by edenhill** [comment]
Thanks for your report, I jush pushed a fix for this: 0c6233d607e3cdb4d034c7e5078db99bffdae2aa
Please download a fresh master version and try again.

**Comment by wushujames** [comment]
Thanks! The %T shows up in usage now, but when I use it, it's not printing out the right timestamps.

```
JChengMBPro15:kafkacat-master-4 jcheng$ ./kafkacat -C -b localhost -t test -o beginning   -f 'Topic %t [%p] at offset %o time %T: key %k: %s\n'
Topic test [0] at offset 0 time 0: key : hi
Topic test [0] at offset 1 time 0: key : timestamp test
Topic test [0] at offset 2 time 0: key : timestamp test
% Reached end of topic test [0] at offset 3
```

When I use the Java `kafka-console-consumer.sh` against the same topic, I can see them:
```
JChengMBPro15:kafka_2.11-0.10.0.0 jcheng$ ./bin/kafka-console-consumer.sh --property print.timestamp=true --new-consumer --bootstrap-server localhost:9092 --topic test --from-beginning
CreateTime:1481936634970	hi
CreateTime:-1	timestamp test
CreateTime:1482051844084	timestamp test
```

**Comment by edenhill** [comment]
You need to enable the new protocol set with `-X api.version.request=true`

**Comment by edenhill** [comment]
api.version.request=true is now automatically enabled if you specify %T

**Comment by wushujames** [comment]
Ha! I was just about to ask if you could make that happen automatically. :)

**Comment by wushujames** [comment]
Works! Thanks Magnus!

```
JChengMBPro15:kafkacat-master-5 jcheng$ kafkacat -C -b 127.0.0.1 -t test -o beginning   -f 'Topic %t [%p] at offset %o time %T: key %k: %s\n'
Topic test [0] at offset 0 time 1481936634970: key : hi
Topic test [0] at offset 1 time -1: key : timestamp test
Topic test [0] at offset 2 time 1482051844084: key : timestamp test
Topic test [0] at offset 3 time -1: key : timestamp test, sent by latest kafkacat
Topic test [0] at offset 4 time -1: key : timestamp test
Topic test [0] at offset 5 time -1: key : timestamp test
Topic test [0] at offset 6 time 1482136046320: key : timestamp test
Topic test [0] at offset 7 time 1482136047951: key : timestamp test
Topic test [0] at offset 8 time 1482136049279: key : timestamp test
Topic test [0] at offset 9 time -1: key : timestamp test
% Reached end of topic test [0] at offset 10
```

**Comment by edenhill** [comment]
Awesome!

**Comment by wushujames** [comment]
It seems like when producing with kafkacat, I also need to specify `-X api.version.request=true` in order to produce timestamps. I thought the broker would auto-assign a timestamp if one was not provided? Or does the broker only add one if I set `log.message.timestamp.type=LogAppend`?

**Comment by edenhill** [comment]
Yes, that's right.
I'm reluctant to enable api.version.request by default just yet since it doesn't work great wih Kafkak broker 0.9.0.0 (due to a broker bug).

**Comment by wushujames** [comment]
Does that mean that messages produced by older clients won't get timestamps? Not even broker-assigned timestamps? Or do I just have to set `log.message.timestamp.type=LogAppend` and then I get broker-assigned timestamps, regardless of the producer?

**Comment by edenhill** [comment]
Afaik yes, that's correct.
I guess what you really want is the broker to default to LogAppend if there is no CreateTime

**Comment by wushujames** [comment]
Yeah, that behavior would make sense to me. _Some_ timestamp is better than nothing. Although I can see that if I didn't know _which_ one had happened (CreateTime or LogAppend), that it might be bad, because my processing of the message might change depending on which one it was.
