### ISSUE TITLE
Unable to consume compressed topics

### ISSUE THREAD

**Issue by ofirsharony** [edenhill/kafkacat#83]
I'm trying to consume our Kafka topics using Kafkacat. 
We were able to successfully consume messages using the the default compression.type (producer, i.e without compression in our case). 
When we changed the compression type to either compression algorithm (gzip / snappy / lz4), the consumption fails immediately with a fatal error.

Here's the command:
`kafkacat -X api.version.request=true -b localhost -t <topic> -o end -C -c 1 -v -p 4 `

And the response received when consuming a topic configured with any of the compression algorithms:
```
% Fatal error at consume_cb:407:
% ERROR: Topic maxwell_with_request_site_sharded [4] error: Message at offset 733099 is too large to fetch, try increasing receive.message.max.bytes
```

The response is the same for all offsets, in different partitions and all our topics.
Please notice the messages size is quite small (smaller than the value of receive.message.max.bytes), 
I'm using the latest Kafka version (0.10.1).

Please advise.
Thanks,

**Comment by edenhill** [comment]
Messages are typically not compressed individually but in larger batches (to improve deflation ratio), so even if your message size is small the compressed messageset/batch may be alot larger and this is is what kafkacat/librdkafka is complaining about.

Did you try increasing `-X receive.message.max.bytes=N`?

What librdkafka version are you on? (`kafkacat -h` should print the librdkafka version in the header).

librdkafka &gt;&eq; 0.9.2 will automatically increase the receive size when it encounters a message that is too large.

**Comment by ofirsharony** [comment]
Thanks for the quick response.
I'm using the latest Kafkacat version:
`Version KAFKACAT_VERSION (librdkafka 0.9.2-RC1)`

As you wrote, shouldn't the 'receive size' increase automatically in such cases?

**Comment by ofirsharony** [comment]
@edenhill Any takes on the above?

**Comment by edenhill** [comment]
What client is producing the message?
Can you try with api.version.request=false?

Can you reproduce this with api.version.request=true and debug=all and provide me the logs?

**Comment by ofirsharony** [comment]
When using api.version.request=false it works with no issues. 
As for the producers, I have the same problem with different types of producers ([Maxwell.io](http://maxwells-daemon.io/) and [KafkaStreams](http://docs.confluent.io/3.1.1/streams/)).
I've sent you the debug logs by email.

**Comment by edenhill** [comment]
I think you might be hitting https://github.com/edenhill/librdkafka/pull/859
Can you upgrade to latest librdkafka master and try to reproduce?

**Comment by ofirsharony** [comment]
Just did, working great with version `librdkafka 0.9.3-pre1`.
Thank you!
