### ISSUE TITLE
High-level balanced KafkaConsumer does not respect -e option

### ISSUE THREAD

**Issue by fsroque** [edenhill/kafkacat#86]
Hi,

When using the balanced high level consumer with the -e flag, it does not exit immediately after the last message is consumed. The -e flags works fine with the regular consumer.

`kafkacat -b mybroker -e -G mygroup topic1`

`% Reached end of topic topic1 [0] at offset 26`

**Comment by edenhill** [comment]
Im working on this

**Comment by anshulbajpai** [comment]
> Im working on this

@edenhill Any updates on this one please?

**Comment by quad2524** [comment]
+1 running into this as well

**Comment by michelazzo** [comment]
I'm running into this problem as well. Is the fix being released anytime soon, @edenhill ?
Thanks

**Comment by hindmasj** [comment]
This is an issue for me too @edenhill. Hope you are well.

**Comment by faust93** [comment]
Same here. Hope it will be fixed someday.
