### ISSUE TITLE
bug with -o when using -G mycg mytopic

### ISSUE THREAD

**Issue by vin-d** [edenhill/kafkacat#88]
I'm trying to read the **oldest** messages from some topic partitions so I do :  
```
kafkacat -G mycg mytopic -b 127.0.0.1  -c 1 -o end
```
or
```
kafkacat -G mycg mytopic -b 127.0.0.1  -c 1 -o beginning
```
i'm not sure which one (but I guess -o beginning).

Then I do the command
```
./kafka-consumer-groups.sh --new-consumer --bootstrap-server 127.0.0.1 --describe --group mycg
```
and I would suspect to see the lag being in one case near 0, in the other case very large (as the number of messages stored on disk for each topic-partition).

but it doesn't seem to work : 
If the group doesn't exist yet the lag is near 0.
If the group already exist it seems it just reads from the stored offset

**Comment by edenhill** [comment]
With -G (high-level consumer) the -o .. switch only sets auto.offset.reset, it does not directly affect the starting offset so the consumer will first try to retrieve stored offsets and then fall back to auto.offset.reset.

Are you expecting it to ignore the stored offset and start with the given -o .. offset for each assigned partition?

**Comment by vin-d** [comment]
Yes I was expecting that it would ignore the stored offset and also set the stored offset at the value of the first message consumed.
So whether the group did or not exist previously, I would do
**kafkacat -G mycg mytopic -b 127.0.0.1  -c 1 -o beginning**
then stop it then just
**kafkacat -G mycg mytopic -b 127.0.0.1  -c 1**
and it would continue to read as if I haven't stopped it the first time and did **-c2**.

But anyway that's an user interface choice/preference, if you decided that it works like it currently does, then... well it's not a bug, it's intended.

Aside from that, when I do (so with the creation of a new cg): 
**kafkacat -G myNewcg1 mytopic -b 127.0.0.1  -c 1 -o beginning**
or
**kafkacat -G myNewcg2 mytopic -b 127.0.0.1  -c 1 -o end**

 it always reads the end of the topic partitions, and this I think is a bug.

**Comment by simplesteph** [comment]
@edenhill How do you use the property? I can't seem to make it work:

```
kafkacat -b localhost:9092-G test-group2 mytopic -X auto.offset.reset=earliest
> does nothing
or
kafkacat -X auto.offset.reset=earliest -b localhost:9092 -G test-group2 mytopic -X auto.offset.reset=earliest
% ERROR: No such configuration property: "auto.offset.reset"
```
FYI
```
kafkacat -b localhost:9092 -o beginning -G lolilosdsl mytopic
% Group lolilosdsl rebalanced (memberid rdkafka-44f41ef7-8a85-4cb9-a2f3-98d07ecbd649): assigned: test [0], test [1], test [2]
% Reached end of topic test [0] at offset 3
% Reached end of topic test [1] at offset 0
% Reached end of topic test [2] at offset 4
```

And 
```
kafkacat -b localhost:9092 -o beginning -t $SOURCE_TOPIC
% Auto-selecting Consumer mode (use -P or -C to override)
hi
hi
hi
% Reached end of topic test [0] at offset 3
% Reached end of topic test [1] at offset 0
hi
hi
hi
hi
% Reached end of topic test [2] at offset 4
```

**Comment by edenhill** [comment]
quick: auto.offset.reset is a topic config property so you need to use `-X topic.auto.offset.reset=earliest`

**Comment by edenhill** [comment]
> `kafkacat -b localhost:9092 -G test-group2 mytopic -X auto.offset.reset=earliest`

Any non -option argument will start the topic name accumulation, so in this command there are three topics:
`mytopic`, `-X` and `auto.offset.reset=earliest`

Make sure to put options before any topics.

**Comment by dkurzaj** [comment]
I can't manage to set the offset of a group at 0 to initialize it. Even though by executing the command in (I think) the right order:
```
$ kafkacat -b localhost:9092 -X topic.auto.offset.reset=earliest -o beginning -G my_group my_topic
```
And apparently `topic.auto.offset.reset` is not in the list of the available librdkafka configuration, because:
```
$ kafkacat -X list | grep topic.auto.offset.reset
```
returns nothing.

I'm running a kafkacat v1.3.0.

**Comment by edenhill** [comment]
Topic configuration is only prefixed with "topic." when you set it, not when it is printed. We're moving away from the topic. prefix to instead rely on the global->topic config fallthru, but that is not yet in kafkacat.
