### ISSUE TITLE
kafkacat exit instead of retrying

### ISSUE THREAD

**Issue by champtar** [edenhill/kafkacat#90]
Hi @edenhill,

I'm using kafkacat + socat as a poor man syslog to kafka forwarder
```
/bin/sh -c "/usr/bin/socat -u tcp4-listen:5515,fork - | /usr/bin/kafkacat -P -b 192.168.1.142,192.168.1.143,192.168.1.144 -t topic"
```

On many errors, exemple https://github.com/edenhill/kafkacat/blob/9deecb5fdb455b824ca0ea501157c16363d4466d/kafkacat.c#L1017
kafkacat exit instead of retrying indefinitely

Is there anything special to do to let librdkafka retry except not calling FATAL?

I'll open a ticket against librdkafka for the "false" error that i see

Thanks
Etienne

**Comment by edenhill** [comment]
What do you think of adding an option not to exit on errors?
The fact is that most errors are recoverable and librdkafka will do its best to do just that, recover.

**Comment by champtar** [comment]
I would even change default behavior and retry by default, adding an option to exit on error (current behavior), because I think that is what most users want

**Comment by champtar** [comment]
@edenhill what do you prefer?

**Comment by edenhill** [comment]
We can't really change the default behaviour since existing users/apps might rely on it, but an `-E` option or similar sounds good.
