### ISSUE TITLE
Tutorial to publish and consume simple JSON messages ?

### ISSUE THREAD

**Issue by c0ze** [edenhill/kafkacat#94]
Is there a way to publish and consume simple JSON payload ?

ie something like :

kafkacat -P -b 127.0.0.1:9001 -t topic | echo '{"message": "some stuff"}'

And then consume it likewise ?

**Comment by edenhill** [comment]
kafkacat doesn't touch or care about the format of the message payload, it is copied as-is to and from kafka.

So you can simply send JSON, one JSON object per line, by piping to kafkacat:
`kafkacat -b <broker> -t <topic>`

Or if you have JSON objects spanning multiple lines you can store each JSON object in a file and then use the file-based approach to producing:
`kafkacat -b <broker> -t <topic> -P <file1> <file2> ..`


For the consumer side you get newline-delimited messages by default, that means that each kafka message ends with a newline (and messages should not contain newlines or the application wont know whats a message delimiter or not).
If your data contains new lines you can change the kafkacat output format with `.. -f "<fmt>"`, e.g. to output arbitrary data prefixed with its length (as a string), do:
`kafkacat -b <broker> -t <topic> -C -f "%S: %s\n"`

See `kafkacat -h` for all supported format string tokens

**Comment by edenhill** [comment]
You can also let kafkacat wrap the received message in JSON, which means the message payload will be escaped in a JSON string, to do this use:
`kafkacat -b <broker> -t <topic> -C -j`

**Comment by edenhill** [comment]
https://docs.confluent.io/current/app-development/kafkacat-usage.html
