### ISSUE TITLE
Producer Random Partitioner Documentation needed

### ISSUE THREAD

**Issue by JohnOmernik** [edenhill/kafkacat#95]
In producer mode -P, the help says -p 1  Use random partitioner

We need more clarification.  With -v here are somethings it shows:
-p 1 
% Message delivered to partition 1 (offset 0)
-p 2
% Message delivered to partition 2 (offset 0)
-p 0
% Message delivered to partition 0 (offset 0)

For all messages, if I leave -p (n) off, then it shows 

% Message delivered to partition -1 (offset 0)
And it appears that -1 is a random partitioner?  Thus I am confused... I just want it to fling messages at random at my partitions... and want to ensure this is happening.

Thanks!

**Comment by edenhill** [comment]
I believe it says that -1 is using random partitioner (which is the default):
`  -p -1              Use random partitioner`
