### ISSUE TITLE
Does kafkacat -L have to talk to multiple brokers?

### ISSUE THREAD

**Issue by wushujames** [edenhill/kafkacat#97]
We use `kafkacat -L` to do get metadata from a broker, as a sort of "liveness" check to see if the broker is functioning and responding to queries.

I had thought that this would work because it just hits that one broker and not other brokers. But it appears that kafkacat will actually reach out to all the other brokers as well? There have been times where one of the brokers is having problems (let say, broker 1) and during those times, `kafkacat -L -b` broker2 will hang or emit error messages saying that it could not reach broker1.

Is my understanding correct? For metadata requests, is it required to reach all the other brokers as well? Or is this simply a consequence of using the same common base code in kafkacat/librdkafka?

**Comment by edenhill** [comment]
The way this works is:
 1. create an internal broker thread for each broker in the bootstrap.servers list
 2. each broker thread immediately tries to connect
 3. the first broker that connects will issue a metadata request to get the full broker list
 4. additional internal broker threads are created from the brokers from the full broker list (unless they exactly match an existing bootstrap.server broker by name and port).

The metadata() (-L) call will happen somewhere in this list, and it will use any broker that is in a fully connected state.

There is currently no way around this, but there are plans in librdkafka to have sparser on-demand connections where it only connects to brokers it actually needs to talk to.

**Comment by wushujames** [comment]
Thanks Magnus! It looks like I will have to live with it for now, or attempt to find some other way of checking liveness of a single broker. Do the kafka Java client libraries expose a way for callers to send Kafka protocol messages to the broker? Like, is there a way I could actually send a Metadata request (protocol Api Key 3: http://kafka.apache.org/protocol.html#protocol_api_keys)? If so, then I could construct a simple program that could call the API.

Sorry, I know that that followup question is not related to kafkacat. Let me know if you'd like me to move that conversation to elsewhere.

**Comment by edenhill** [comment]
Not sure about the Java client, but I think Ive seen kafka-python exposing protocol primitives:
https://github.com/dpkp/kafka-python

But it is an interesting use-case and I guess it makes sense for kafkacat to have some kind of more boolean usage to check if a broker or cluster is available.
What exactly is it that you want to check?
 * that a single broker is up?
 * that a list of brokers are all up?
 * that all brokers in the cluster are up?
 * that a specific topic and partition has a leader that is up? 
 ..
?

**Comment by wushujames** [comment]
That a single broker is up. I want to do more than just "is the port open". I want to test that Kafka is actually functioning, but I don't want to go as far as producing/consuming.

We're currently using it in one of our health checks. More specifically, we have a load balancer in front of our brokers. Clients can use that load balancer's IP address as a single discovery point to contact Kafka. The load balancer calls an HTTP endpoint running alongside our brokers, which does a metadata request to the broker to see whether it is alive. The load balancer uses that to determine whether to add/remove brokers from the load balancer pool.

**Comment by edenhill** [comment]
Okay, thanks for the details.

Do note that a full metadata request may be somewhat costly on a cluster with many topics and partitions.
The alternative is to use a metadata request specifying a single topic, which is cheaper, but with automatic topic creation on the broker this might have undesired side-effects.
The latest protocol version of MetadataRequest solves the latter by allowing a client to only request the broker list, but it requires broker version 0.10..something.

**Comment by wushujames** [comment]
When you say "costly", what is the cost? Is it the bandwidth and CPU time to serialize the in-memory metadata onto the wire? Or is there more to it than that?

**Comment by edenhill** [comment]
The amazing @ijuma's explanation:
> It's CPU bound as it's served from the metadata cache
> For large clusters, the number of operations to build the response is quite large. we've optimised it quite a bit for 0.9.0.x, but it could be improved further if we changed the metadata response class. > It's currently uses a Node, which makes sense for the Java clients, but is not necessary for the broker

**Comment by wushujames** [comment]
Interesting. Thanks. When you say "large cluster", I'm guessing you mean in terms of a large number of topics/partitions? Number of brokers doesn't matter, right? So a small number of brokers with a large number of total partitions would be "expensive"?

**Comment by edenhill** [comment]
That is my understanding as well, yeah.

**Comment by wushujames** [comment]
Thanks Magnus. I'll look into doing a check of a single topic, for liveness. We have other cases where we actually want all the metadata, to do stuff like https://github.com/wushujames/kafka-utilities/tree/master/who_in_isr

Anyway, thanks for the info. I'll close the issue.

**Comment by ijuma** [comment]
The innermost statement of the innermost loop is executed (numTopics * numPartitions * aliveReplicas) + (numTopics * numPartitions * aliveIsr) times. So those are the parameters that make a difference.

**Comment by ijuma** [comment]
And to answer "Do the kafka Java client libraries expose a way for callers to send Kafka protocol messages to the broker? Like, is there a way I could actually send a Metadata request (protocol Api Key 3: http://kafka.apache.org/protocol.html#protocol_api_keys)? If so, then I could construct a simple program that could call the API."

The AdminClient will provide some APIs that do things like this. It is not intended to be a generic way to invoke any protocol though.
