### ISSUE TITLE
LNK2019 Bug: query_offsets_by_time (WIN32 code)

### ISSUE THREAD

**Issue by fignutz** [edenhill/kafkacat#99]
This originally would not compile because the function `query_offsets_by_time` is declared but not defined (`kafkacat.c`); caused a LNK2019 error upon compilation. This is defined in the header, but the linker is unable to resolve the function correctly. The band-aid for now is to simply comment out the offending line (1490) and rebuild. This build was completed in **_MVS2017_**. This, of course, effectively cripples the _Query_ option, but I don't need it for my use case.

**Comment by edenhill** [comment]
Probably due to missing tools.c import, which is fixed.
